###################  开发环境配置     ###################
#info一般配置用户自定义信息，在actuatr的/info端点可显示（使用@***@从pom.xml中获取信息）
info:
  log-switch: 
    service: true
  
server:
  port: 8083
  context-path: / #设定应用的context-path
    
spring:
  profiles: dev  
  application: 
    name: crm-ocrm

mybatis:
  mapper-packages:  cn.com.zsyk.crm.ocrm.mapper        #Mapper接口扫描目录
  mapper-locations: classpath:mapper/ocrm/*.xml       #xml文件扫描目录
  type-aliases-package: cn.com.zsyk.crm.ocrm.entity    #别名扫描目录  
