package cn.com.zsyk.crm.ecif.entity;

import java.io.Serializable;
import java.util.Date;

public class EcContactWay implements Serializable {
    private String custSource;

    public String getCustSource() {
        return custSource;
    }

    public void setCustSource(String custSource) {
        this.custSource = custSource;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.cust_no
     *
     * @mbggenerated
     */
    private String custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.contact_sqn
     *
     * @mbggenerated
     */
    private Integer contactSqn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.contact_nam
     *
     * @mbggenerated
     */
    private String contactNam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.phone_no1
     *
     * @mbggenerated
     */
    private String phoneNo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.phone_no2
     *
     * @mbggenerated
     */
    private String phoneNo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.phone_no3
     *
     * @mbggenerated
     */
    private String phoneNo3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.telephone1
     *
     * @mbggenerated
     */
    private String telephone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.telephone2
     *
     * @mbggenerated
     */
    private String telephone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.wechat_no
     *
     * @mbggenerated
     */
    private String wechatNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.email_addr
     *
     * @mbggenerated
     */
    private String emailAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.wht_default_way
     *
     * @mbggenerated
     */
    private String whtDefaultWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.microblog
     *
     * @mbggenerated
     */
    private String microblog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.alipay
     *
     * @mbggenerated
     */
    private String alipay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.update_date
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.time_stamp
     *
     * @mbggenerated
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_contact_way.rec_stat
     *
     * @mbggenerated
     */
    private String recStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ec_contact_way
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.cust_no
     *
     * @return the value of ec_contact_way.cust_no
     *
     * @mbggenerated
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.cust_no
     *
     * @param custNo the value for ec_contact_way.cust_no
     *
     * @mbggenerated
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.contact_sqn
     *
     * @return the value of ec_contact_way.contact_sqn
     *
     * @mbggenerated
     */
    public Integer getContactSqn() {
        return contactSqn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.contact_sqn
     *
     * @param contactSqn the value for ec_contact_way.contact_sqn
     *
     * @mbggenerated
     */
    public void setContactSqn(Integer contactSqn) {
        this.contactSqn = contactSqn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.contact_nam
     *
     * @return the value of ec_contact_way.contact_nam
     *
     * @mbggenerated
     */
    public String getContactNam() {
        return contactNam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.contact_nam
     *
     * @param contactNam the value for ec_contact_way.contact_nam
     *
     * @mbggenerated
     */
    public void setContactNam(String contactNam) {
        this.contactNam = contactNam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.phone_no1
     *
     * @return the value of ec_contact_way.phone_no1
     *
     * @mbggenerated
     */
    public String getPhoneNo1() {
        return phoneNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.phone_no1
     *
     * @param phoneNo1 the value for ec_contact_way.phone_no1
     *
     * @mbggenerated
     */
    public void setPhoneNo1(String phoneNo1) {
        this.phoneNo1 = phoneNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.phone_no2
     *
     * @return the value of ec_contact_way.phone_no2
     *
     * @mbggenerated
     */
    public String getPhoneNo2() {
        return phoneNo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.phone_no2
     *
     * @param phoneNo2 the value for ec_contact_way.phone_no2
     *
     * @mbggenerated
     */
    public void setPhoneNo2(String phoneNo2) {
        this.phoneNo2 = phoneNo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.phone_no3
     *
     * @return the value of ec_contact_way.phone_no3
     *
     * @mbggenerated
     */
    public String getPhoneNo3() {
        return phoneNo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.phone_no3
     *
     * @param phoneNo3 the value for ec_contact_way.phone_no3
     *
     * @mbggenerated
     */
    public void setPhoneNo3(String phoneNo3) {
        this.phoneNo3 = phoneNo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.telephone1
     *
     * @return the value of ec_contact_way.telephone1
     *
     * @mbggenerated
     */
    public String getTelephone1() {
        return telephone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.telephone1
     *
     * @param telephone1 the value for ec_contact_way.telephone1
     *
     * @mbggenerated
     */
    public void setTelephone1(String telephone1) {
        this.telephone1 = telephone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.telephone2
     *
     * @return the value of ec_contact_way.telephone2
     *
     * @mbggenerated
     */
    public String getTelephone2() {
        return telephone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.telephone2
     *
     * @param telephone2 the value for ec_contact_way.telephone2
     *
     * @mbggenerated
     */
    public void setTelephone2(String telephone2) {
        this.telephone2 = telephone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.wechat_no
     *
     * @return the value of ec_contact_way.wechat_no
     *
     * @mbggenerated
     */
    public String getWechatNo() {
        return wechatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.wechat_no
     *
     * @param wechatNo the value for ec_contact_way.wechat_no
     *
     * @mbggenerated
     */
    public void setWechatNo(String wechatNo) {
        this.wechatNo = wechatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.email_addr
     *
     * @return the value of ec_contact_way.email_addr
     *
     * @mbggenerated
     */
    public String getEmailAddr() {
        return emailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.email_addr
     *
     * @param emailAddr the value for ec_contact_way.email_addr
     *
     * @mbggenerated
     */
    public void setEmailAddr(String emailAddr) {
        this.emailAddr = emailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.fax
     *
     * @return the value of ec_contact_way.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.fax
     *
     * @param fax the value for ec_contact_way.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.wht_default_way
     *
     * @return the value of ec_contact_way.wht_default_way
     *
     * @mbggenerated
     */
    public String getWhtDefaultWay() {
        return whtDefaultWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.wht_default_way
     *
     * @param whtDefaultWay the value for ec_contact_way.wht_default_way
     *
     * @mbggenerated
     */
    public void setWhtDefaultWay(String whtDefaultWay) {
        this.whtDefaultWay = whtDefaultWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.qq
     *
     * @return the value of ec_contact_way.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.qq
     *
     * @param qq the value for ec_contact_way.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.microblog
     *
     * @return the value of ec_contact_way.microblog
     *
     * @mbggenerated
     */
    public String getMicroblog() {
        return microblog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.microblog
     *
     * @param microblog the value for ec_contact_way.microblog
     *
     * @mbggenerated
     */
    public void setMicroblog(String microblog) {
        this.microblog = microblog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.alipay
     *
     * @return the value of ec_contact_way.alipay
     *
     * @mbggenerated
     */
    public String getAlipay() {
        return alipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.alipay
     *
     * @param alipay the value for ec_contact_way.alipay
     *
     * @mbggenerated
     */
    public void setAlipay(String alipay) {
        this.alipay = alipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.create_date
     *
     * @return the value of ec_contact_way.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.create_date
     *
     * @param createDate the value for ec_contact_way.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.create_time
     *
     * @return the value of ec_contact_way.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.create_time
     *
     * @param createTime the value for ec_contact_way.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.create_user
     *
     * @return the value of ec_contact_way.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.create_user
     *
     * @param createUser the value for ec_contact_way.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.update_date
     *
     * @return the value of ec_contact_way.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.update_date
     *
     * @param updateDate the value for ec_contact_way.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.update_time
     *
     * @return the value of ec_contact_way.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.update_time
     *
     * @param updateTime the value for ec_contact_way.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.update_user
     *
     * @return the value of ec_contact_way.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.update_user
     *
     * @param updateUser the value for ec_contact_way.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.time_stamp
     *
     * @return the value of ec_contact_way.time_stamp
     *
     * @mbggenerated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.time_stamp
     *
     * @param timeStamp the value for ec_contact_way.time_stamp
     *
     * @mbggenerated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_contact_way.rec_stat
     *
     * @return the value of ec_contact_way.rec_stat
     *
     * @mbggenerated
     */
    public String getRecStat() {
        return recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_contact_way.rec_stat
     *
     * @param recStat the value for ec_contact_way.rec_stat
     *
     * @mbggenerated
     */
    public void setRecStat(String recStat) {
        this.recStat = recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_contact_way
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EcContactWay other = (EcContactWay) that;
        return (this.getCustNo() == null ? other.getCustNo() == null : this.getCustNo().equals(other.getCustNo()))
            && (this.getContactSqn() == null ? other.getContactSqn() == null : this.getContactSqn().equals(other.getContactSqn()))
            && (this.getContactNam() == null ? other.getContactNam() == null : this.getContactNam().equals(other.getContactNam()))
            && (this.getPhoneNo1() == null ? other.getPhoneNo1() == null : this.getPhoneNo1().equals(other.getPhoneNo1()))
            && (this.getPhoneNo2() == null ? other.getPhoneNo2() == null : this.getPhoneNo2().equals(other.getPhoneNo2()))
            && (this.getPhoneNo3() == null ? other.getPhoneNo3() == null : this.getPhoneNo3().equals(other.getPhoneNo3()))
            && (this.getTelephone1() == null ? other.getTelephone1() == null : this.getTelephone1().equals(other.getTelephone1()))
            && (this.getTelephone2() == null ? other.getTelephone2() == null : this.getTelephone2().equals(other.getTelephone2()))
            && (this.getWechatNo() == null ? other.getWechatNo() == null : this.getWechatNo().equals(other.getWechatNo()))
            && (this.getEmailAddr() == null ? other.getEmailAddr() == null : this.getEmailAddr().equals(other.getEmailAddr()))
            && (this.getFax() == null ? other.getFax() == null : this.getFax().equals(other.getFax()))
            && (this.getWhtDefaultWay() == null ? other.getWhtDefaultWay() == null : this.getWhtDefaultWay().equals(other.getWhtDefaultWay()))
            && (this.getQq() == null ? other.getQq() == null : this.getQq().equals(other.getQq()))
            && (this.getMicroblog() == null ? other.getMicroblog() == null : this.getMicroblog().equals(other.getMicroblog()))
            && (this.getAlipay() == null ? other.getAlipay() == null : this.getAlipay().equals(other.getAlipay()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getTimeStamp() == null ? other.getTimeStamp() == null : this.getTimeStamp().equals(other.getTimeStamp()))
            && (this.getRecStat() == null ? other.getRecStat() == null : this.getRecStat().equals(other.getRecStat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_contact_way
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCustNo() == null) ? 0 : getCustNo().hashCode());
        result = prime * result + ((getContactSqn() == null) ? 0 : getContactSqn().hashCode());
        result = prime * result + ((getContactNam() == null) ? 0 : getContactNam().hashCode());
        result = prime * result + ((getPhoneNo1() == null) ? 0 : getPhoneNo1().hashCode());
        result = prime * result + ((getPhoneNo2() == null) ? 0 : getPhoneNo2().hashCode());
        result = prime * result + ((getPhoneNo3() == null) ? 0 : getPhoneNo3().hashCode());
        result = prime * result + ((getTelephone1() == null) ? 0 : getTelephone1().hashCode());
        result = prime * result + ((getTelephone2() == null) ? 0 : getTelephone2().hashCode());
        result = prime * result + ((getWechatNo() == null) ? 0 : getWechatNo().hashCode());
        result = prime * result + ((getEmailAddr() == null) ? 0 : getEmailAddr().hashCode());
        result = prime * result + ((getFax() == null) ? 0 : getFax().hashCode());
        result = prime * result + ((getWhtDefaultWay() == null) ? 0 : getWhtDefaultWay().hashCode());
        result = prime * result + ((getQq() == null) ? 0 : getQq().hashCode());
        result = prime * result + ((getMicroblog() == null) ? 0 : getMicroblog().hashCode());
        result = prime * result + ((getAlipay() == null) ? 0 : getAlipay().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getTimeStamp() == null) ? 0 : getTimeStamp().hashCode());
        result = prime * result + ((getRecStat() == null) ? 0 : getRecStat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_contact_way
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", custNo=").append(custNo);
        sb.append(", contactSqn=").append(contactSqn);
        sb.append(", contactNam=").append(contactNam);
        sb.append(", phoneNo1=").append(phoneNo1);
        sb.append(", phoneNo2=").append(phoneNo2);
        sb.append(", phoneNo3=").append(phoneNo3);
        sb.append(", telephone1=").append(telephone1);
        sb.append(", telephone2=").append(telephone2);
        sb.append(", wechatNo=").append(wechatNo);
        sb.append(", emailAddr=").append(emailAddr);
        sb.append(", fax=").append(fax);
        sb.append(", whtDefaultWay=").append(whtDefaultWay);
        sb.append(", qq=").append(qq);
        sb.append(", microblog=").append(microblog);
        sb.append(", alipay=").append(alipay);
        sb.append(", createDate=").append(createDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", recStat=").append(recStat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}