package cn.com.zsyk.crm.ecif.entity;

import java.io.Serializable;
import java.util.Date;

public class EcCustAgent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.cust_no
     *
     * @mbggenerated
     */
    private String custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.orig_sys_agent_no
     *
     * @mbggenerated
     */
    private String origSysAgentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.agent_devcom_cd
     *
     * @mbggenerated
     */
    private String agentDevcomCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.agent_kind
     *
     * @mbggenerated
     */
    private String agentKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.bln_chnl
     *
     * @mbggenerated
     */
    private String blnChnl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.perf_grade
     *
     * @mbggenerated
     */
    private String perfGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.credit_grade
     *
     * @mbggenerated
     */
    private String creditGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.inwork_date
     *
     * @mbggenerated
     */
    private String inworkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.agent_sts
     *
     * @mbggenerated
     */
    private String agentSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.outwork_date
     *
     * @mbggenerated
     */
    private String outworkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.posit_grade
     *
     * @mbggenerated
     */
    private String positGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.update_date
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.time_stamp
     *
     * @mbggenerated
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_agent.rec_stat
     *
     * @mbggenerated
     */
    private String recStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ec_cust_agent
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.cust_no
     *
     * @return the value of ec_cust_agent.cust_no
     *
     * @mbggenerated
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.cust_no
     *
     * @param custNo the value for ec_cust_agent.cust_no
     *
     * @mbggenerated
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.orig_sys_agent_no
     *
     * @return the value of ec_cust_agent.orig_sys_agent_no
     *
     * @mbggenerated
     */
    public String getOrigSysAgentNo() {
        return origSysAgentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.orig_sys_agent_no
     *
     * @param origSysAgentNo the value for ec_cust_agent.orig_sys_agent_no
     *
     * @mbggenerated
     */
    public void setOrigSysAgentNo(String origSysAgentNo) {
        this.origSysAgentNo = origSysAgentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.agent_devcom_cd
     *
     * @return the value of ec_cust_agent.agent_devcom_cd
     *
     * @mbggenerated
     */
    public String getAgentDevcomCd() {
        return agentDevcomCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.agent_devcom_cd
     *
     * @param agentDevcomCd the value for ec_cust_agent.agent_devcom_cd
     *
     * @mbggenerated
     */
    public void setAgentDevcomCd(String agentDevcomCd) {
        this.agentDevcomCd = agentDevcomCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.agent_kind
     *
     * @return the value of ec_cust_agent.agent_kind
     *
     * @mbggenerated
     */
    public String getAgentKind() {
        return agentKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.agent_kind
     *
     * @param agentKind the value for ec_cust_agent.agent_kind
     *
     * @mbggenerated
     */
    public void setAgentKind(String agentKind) {
        this.agentKind = agentKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.bln_chnl
     *
     * @return the value of ec_cust_agent.bln_chnl
     *
     * @mbggenerated
     */
    public String getBlnChnl() {
        return blnChnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.bln_chnl
     *
     * @param blnChnl the value for ec_cust_agent.bln_chnl
     *
     * @mbggenerated
     */
    public void setBlnChnl(String blnChnl) {
        this.blnChnl = blnChnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.perf_grade
     *
     * @return the value of ec_cust_agent.perf_grade
     *
     * @mbggenerated
     */
    public String getPerfGrade() {
        return perfGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.perf_grade
     *
     * @param perfGrade the value for ec_cust_agent.perf_grade
     *
     * @mbggenerated
     */
    public void setPerfGrade(String perfGrade) {
        this.perfGrade = perfGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.credit_grade
     *
     * @return the value of ec_cust_agent.credit_grade
     *
     * @mbggenerated
     */
    public String getCreditGrade() {
        return creditGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.credit_grade
     *
     * @param creditGrade the value for ec_cust_agent.credit_grade
     *
     * @mbggenerated
     */
    public void setCreditGrade(String creditGrade) {
        this.creditGrade = creditGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.inwork_date
     *
     * @return the value of ec_cust_agent.inwork_date
     *
     * @mbggenerated
     */
    public String getInworkDate() {
        return inworkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.inwork_date
     *
     * @param inworkDate the value for ec_cust_agent.inwork_date
     *
     * @mbggenerated
     */
    public void setInworkDate(String inworkDate) {
        this.inworkDate = inworkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.agent_sts
     *
     * @return the value of ec_cust_agent.agent_sts
     *
     * @mbggenerated
     */
    public String getAgentSts() {
        return agentSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.agent_sts
     *
     * @param agentSts the value for ec_cust_agent.agent_sts
     *
     * @mbggenerated
     */
    public void setAgentSts(String agentSts) {
        this.agentSts = agentSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.outwork_date
     *
     * @return the value of ec_cust_agent.outwork_date
     *
     * @mbggenerated
     */
    public String getOutworkDate() {
        return outworkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.outwork_date
     *
     * @param outworkDate the value for ec_cust_agent.outwork_date
     *
     * @mbggenerated
     */
    public void setOutworkDate(String outworkDate) {
        this.outworkDate = outworkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.posit_grade
     *
     * @return the value of ec_cust_agent.posit_grade
     *
     * @mbggenerated
     */
    public String getPositGrade() {
        return positGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.posit_grade
     *
     * @param positGrade the value for ec_cust_agent.posit_grade
     *
     * @mbggenerated
     */
    public void setPositGrade(String positGrade) {
        this.positGrade = positGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.create_date
     *
     * @return the value of ec_cust_agent.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.create_date
     *
     * @param createDate the value for ec_cust_agent.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.create_time
     *
     * @return the value of ec_cust_agent.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.create_time
     *
     * @param createTime the value for ec_cust_agent.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.create_user
     *
     * @return the value of ec_cust_agent.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.create_user
     *
     * @param createUser the value for ec_cust_agent.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.update_date
     *
     * @return the value of ec_cust_agent.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.update_date
     *
     * @param updateDate the value for ec_cust_agent.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.update_time
     *
     * @return the value of ec_cust_agent.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.update_time
     *
     * @param updateTime the value for ec_cust_agent.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.update_user
     *
     * @return the value of ec_cust_agent.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.update_user
     *
     * @param updateUser the value for ec_cust_agent.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.time_stamp
     *
     * @return the value of ec_cust_agent.time_stamp
     *
     * @mbggenerated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.time_stamp
     *
     * @param timeStamp the value for ec_cust_agent.time_stamp
     *
     * @mbggenerated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_agent.rec_stat
     *
     * @return the value of ec_cust_agent.rec_stat
     *
     * @mbggenerated
     */
    public String getRecStat() {
        return recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_agent.rec_stat
     *
     * @param recStat the value for ec_cust_agent.rec_stat
     *
     * @mbggenerated
     */
    public void setRecStat(String recStat) {
        this.recStat = recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_agent
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EcCustAgent other = (EcCustAgent) that;
        return (this.getCustNo() == null ? other.getCustNo() == null : this.getCustNo().equals(other.getCustNo()))
            && (this.getOrigSysAgentNo() == null ? other.getOrigSysAgentNo() == null : this.getOrigSysAgentNo().equals(other.getOrigSysAgentNo()))
            && (this.getAgentDevcomCd() == null ? other.getAgentDevcomCd() == null : this.getAgentDevcomCd().equals(other.getAgentDevcomCd()))
            && (this.getAgentKind() == null ? other.getAgentKind() == null : this.getAgentKind().equals(other.getAgentKind()))
            && (this.getBlnChnl() == null ? other.getBlnChnl() == null : this.getBlnChnl().equals(other.getBlnChnl()))
            && (this.getPerfGrade() == null ? other.getPerfGrade() == null : this.getPerfGrade().equals(other.getPerfGrade()))
            && (this.getCreditGrade() == null ? other.getCreditGrade() == null : this.getCreditGrade().equals(other.getCreditGrade()))
            && (this.getInworkDate() == null ? other.getInworkDate() == null : this.getInworkDate().equals(other.getInworkDate()))
            && (this.getAgentSts() == null ? other.getAgentSts() == null : this.getAgentSts().equals(other.getAgentSts()))
            && (this.getOutworkDate() == null ? other.getOutworkDate() == null : this.getOutworkDate().equals(other.getOutworkDate()))
            && (this.getPositGrade() == null ? other.getPositGrade() == null : this.getPositGrade().equals(other.getPositGrade()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getTimeStamp() == null ? other.getTimeStamp() == null : this.getTimeStamp().equals(other.getTimeStamp()))
            && (this.getRecStat() == null ? other.getRecStat() == null : this.getRecStat().equals(other.getRecStat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_agent
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCustNo() == null) ? 0 : getCustNo().hashCode());
        result = prime * result + ((getOrigSysAgentNo() == null) ? 0 : getOrigSysAgentNo().hashCode());
        result = prime * result + ((getAgentDevcomCd() == null) ? 0 : getAgentDevcomCd().hashCode());
        result = prime * result + ((getAgentKind() == null) ? 0 : getAgentKind().hashCode());
        result = prime * result + ((getBlnChnl() == null) ? 0 : getBlnChnl().hashCode());
        result = prime * result + ((getPerfGrade() == null) ? 0 : getPerfGrade().hashCode());
        result = prime * result + ((getCreditGrade() == null) ? 0 : getCreditGrade().hashCode());
        result = prime * result + ((getInworkDate() == null) ? 0 : getInworkDate().hashCode());
        result = prime * result + ((getAgentSts() == null) ? 0 : getAgentSts().hashCode());
        result = prime * result + ((getOutworkDate() == null) ? 0 : getOutworkDate().hashCode());
        result = prime * result + ((getPositGrade() == null) ? 0 : getPositGrade().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getTimeStamp() == null) ? 0 : getTimeStamp().hashCode());
        result = prime * result + ((getRecStat() == null) ? 0 : getRecStat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_agent
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", custNo=").append(custNo);
        sb.append(", origSysAgentNo=").append(origSysAgentNo);
        sb.append(", agentDevcomCd=").append(agentDevcomCd);
        sb.append(", agentKind=").append(agentKind);
        sb.append(", blnChnl=").append(blnChnl);
        sb.append(", perfGrade=").append(perfGrade);
        sb.append(", creditGrade=").append(creditGrade);
        sb.append(", inworkDate=").append(inworkDate);
        sb.append(", agentSts=").append(agentSts);
        sb.append(", outworkDate=").append(outworkDate);
        sb.append(", positGrade=").append(positGrade);
        sb.append(", createDate=").append(createDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", recStat=").append(recStat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}