package cn.com.zsyk.crm.ecif.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class EcCustProduct implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.cust_no
     *
     * @mbggenerated
     */
    private String custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.product_cd
     *
     * @mbggenerated
     */
    private String productCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.product_typ
     *
     * @mbggenerated
     */
    private String productTyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.product_nam
     *
     * @mbggenerated
     */
    private String productNam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.eff_date
     *
     * @mbggenerated
     */
    private String effDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.exp_date
     *
     * @mbggenerated
     */
    private String expDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.valid_sts
     *
     * @mbggenerated
     */
    private String validSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.pay_bank
     *
     * @mbggenerated
     */
    private String payBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.pay_ac
     *
     * @mbggenerated
     */
    private String payAc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.pay_years
     *
     * @mbggenerated
     */
    private Integer payYears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.pay_tm
     *
     * @mbggenerated
     */
    private Integer payTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.pay_amt
     *
     * @mbggenerated
     */
    private BigDecimal payAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.pay_date
     *
     * @mbggenerated
     */
    private String payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.pay_mode
     *
     * @mbggenerated
     */
    private String payMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.pay_chnl
     *
     * @mbggenerated
     */
    private String payChnl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.payer
     *
     * @mbggenerated
     */
    private String payer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.policy_holder
     *
     * @mbggenerated
     */
    private String policyHolder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.beneficiary
     *
     * @mbggenerated
     */
    private String beneficiary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.update_date
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.time_stamp
     *
     * @mbggenerated
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_product.rec_stat
     *
     * @mbggenerated
     */
    private String recStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ec_cust_product
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.cust_no
     *
     * @return the value of ec_cust_product.cust_no
     *
     * @mbggenerated
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.cust_no
     *
     * @param custNo the value for ec_cust_product.cust_no
     *
     * @mbggenerated
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.product_cd
     *
     * @return the value of ec_cust_product.product_cd
     *
     * @mbggenerated
     */
    public String getProductCd() {
        return productCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.product_cd
     *
     * @param productCd the value for ec_cust_product.product_cd
     *
     * @mbggenerated
     */
    public void setProductCd(String productCd) {
        this.productCd = productCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.product_typ
     *
     * @return the value of ec_cust_product.product_typ
     *
     * @mbggenerated
     */
    public String getProductTyp() {
        return productTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.product_typ
     *
     * @param productTyp the value for ec_cust_product.product_typ
     *
     * @mbggenerated
     */
    public void setProductTyp(String productTyp) {
        this.productTyp = productTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.product_nam
     *
     * @return the value of ec_cust_product.product_nam
     *
     * @mbggenerated
     */
    public String getProductNam() {
        return productNam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.product_nam
     *
     * @param productNam the value for ec_cust_product.product_nam
     *
     * @mbggenerated
     */
    public void setProductNam(String productNam) {
        this.productNam = productNam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.eff_date
     *
     * @return the value of ec_cust_product.eff_date
     *
     * @mbggenerated
     */
    public String getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.eff_date
     *
     * @param effDate the value for ec_cust_product.eff_date
     *
     * @mbggenerated
     */
    public void setEffDate(String effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.exp_date
     *
     * @return the value of ec_cust_product.exp_date
     *
     * @mbggenerated
     */
    public String getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.exp_date
     *
     * @param expDate the value for ec_cust_product.exp_date
     *
     * @mbggenerated
     */
    public void setExpDate(String expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.valid_sts
     *
     * @return the value of ec_cust_product.valid_sts
     *
     * @mbggenerated
     */
    public String getValidSts() {
        return validSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.valid_sts
     *
     * @param validSts the value for ec_cust_product.valid_sts
     *
     * @mbggenerated
     */
    public void setValidSts(String validSts) {
        this.validSts = validSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.pay_bank
     *
     * @return the value of ec_cust_product.pay_bank
     *
     * @mbggenerated
     */
    public String getPayBank() {
        return payBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.pay_bank
     *
     * @param payBank the value for ec_cust_product.pay_bank
     *
     * @mbggenerated
     */
    public void setPayBank(String payBank) {
        this.payBank = payBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.pay_ac
     *
     * @return the value of ec_cust_product.pay_ac
     *
     * @mbggenerated
     */
    public String getPayAc() {
        return payAc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.pay_ac
     *
     * @param payAc the value for ec_cust_product.pay_ac
     *
     * @mbggenerated
     */
    public void setPayAc(String payAc) {
        this.payAc = payAc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.pay_years
     *
     * @return the value of ec_cust_product.pay_years
     *
     * @mbggenerated
     */
    public Integer getPayYears() {
        return payYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.pay_years
     *
     * @param payYears the value for ec_cust_product.pay_years
     *
     * @mbggenerated
     */
    public void setPayYears(Integer payYears) {
        this.payYears = payYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.pay_tm
     *
     * @return the value of ec_cust_product.pay_tm
     *
     * @mbggenerated
     */
    public Integer getPayTm() {
        return payTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.pay_tm
     *
     * @param payTm the value for ec_cust_product.pay_tm
     *
     * @mbggenerated
     */
    public void setPayTm(Integer payTm) {
        this.payTm = payTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.pay_amt
     *
     * @return the value of ec_cust_product.pay_amt
     *
     * @mbggenerated
     */
    public BigDecimal getPayAmt() {
        return payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.pay_amt
     *
     * @param payAmt the value for ec_cust_product.pay_amt
     *
     * @mbggenerated
     */
    public void setPayAmt(BigDecimal payAmt) {
        this.payAmt = payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.pay_date
     *
     * @return the value of ec_cust_product.pay_date
     *
     * @mbggenerated
     */
    public String getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.pay_date
     *
     * @param payDate the value for ec_cust_product.pay_date
     *
     * @mbggenerated
     */
    public void setPayDate(String payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.pay_mode
     *
     * @return the value of ec_cust_product.pay_mode
     *
     * @mbggenerated
     */
    public String getPayMode() {
        return payMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.pay_mode
     *
     * @param payMode the value for ec_cust_product.pay_mode
     *
     * @mbggenerated
     */
    public void setPayMode(String payMode) {
        this.payMode = payMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.pay_chnl
     *
     * @return the value of ec_cust_product.pay_chnl
     *
     * @mbggenerated
     */
    public String getPayChnl() {
        return payChnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.pay_chnl
     *
     * @param payChnl the value for ec_cust_product.pay_chnl
     *
     * @mbggenerated
     */
    public void setPayChnl(String payChnl) {
        this.payChnl = payChnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.payer
     *
     * @return the value of ec_cust_product.payer
     *
     * @mbggenerated
     */
    public String getPayer() {
        return payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.payer
     *
     * @param payer the value for ec_cust_product.payer
     *
     * @mbggenerated
     */
    public void setPayer(String payer) {
        this.payer = payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.policy_holder
     *
     * @return the value of ec_cust_product.policy_holder
     *
     * @mbggenerated
     */
    public String getPolicyHolder() {
        return policyHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.policy_holder
     *
     * @param policyHolder the value for ec_cust_product.policy_holder
     *
     * @mbggenerated
     */
    public void setPolicyHolder(String policyHolder) {
        this.policyHolder = policyHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.beneficiary
     *
     * @return the value of ec_cust_product.beneficiary
     *
     * @mbggenerated
     */
    public String getBeneficiary() {
        return beneficiary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.beneficiary
     *
     * @param beneficiary the value for ec_cust_product.beneficiary
     *
     * @mbggenerated
     */
    public void setBeneficiary(String beneficiary) {
        this.beneficiary = beneficiary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.create_date
     *
     * @return the value of ec_cust_product.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.create_date
     *
     * @param createDate the value for ec_cust_product.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.create_time
     *
     * @return the value of ec_cust_product.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.create_time
     *
     * @param createTime the value for ec_cust_product.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.create_user
     *
     * @return the value of ec_cust_product.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.create_user
     *
     * @param createUser the value for ec_cust_product.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.update_date
     *
     * @return the value of ec_cust_product.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.update_date
     *
     * @param updateDate the value for ec_cust_product.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.update_time
     *
     * @return the value of ec_cust_product.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.update_time
     *
     * @param updateTime the value for ec_cust_product.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.update_user
     *
     * @return the value of ec_cust_product.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.update_user
     *
     * @param updateUser the value for ec_cust_product.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.time_stamp
     *
     * @return the value of ec_cust_product.time_stamp
     *
     * @mbggenerated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.time_stamp
     *
     * @param timeStamp the value for ec_cust_product.time_stamp
     *
     * @mbggenerated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_product.rec_stat
     *
     * @return the value of ec_cust_product.rec_stat
     *
     * @mbggenerated
     */
    public String getRecStat() {
        return recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_product.rec_stat
     *
     * @param recStat the value for ec_cust_product.rec_stat
     *
     * @mbggenerated
     */
    public void setRecStat(String recStat) {
        this.recStat = recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_product
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EcCustProduct other = (EcCustProduct) that;
        return (this.getCustNo() == null ? other.getCustNo() == null : this.getCustNo().equals(other.getCustNo()))
            && (this.getProductCd() == null ? other.getProductCd() == null : this.getProductCd().equals(other.getProductCd()))
            && (this.getProductTyp() == null ? other.getProductTyp() == null : this.getProductTyp().equals(other.getProductTyp()))
            && (this.getProductNam() == null ? other.getProductNam() == null : this.getProductNam().equals(other.getProductNam()))
            && (this.getEffDate() == null ? other.getEffDate() == null : this.getEffDate().equals(other.getEffDate()))
            && (this.getExpDate() == null ? other.getExpDate() == null : this.getExpDate().equals(other.getExpDate()))
            && (this.getValidSts() == null ? other.getValidSts() == null : this.getValidSts().equals(other.getValidSts()))
            && (this.getPayBank() == null ? other.getPayBank() == null : this.getPayBank().equals(other.getPayBank()))
            && (this.getPayAc() == null ? other.getPayAc() == null : this.getPayAc().equals(other.getPayAc()))
            && (this.getPayYears() == null ? other.getPayYears() == null : this.getPayYears().equals(other.getPayYears()))
            && (this.getPayTm() == null ? other.getPayTm() == null : this.getPayTm().equals(other.getPayTm()))
            && (this.getPayAmt() == null ? other.getPayAmt() == null : this.getPayAmt().equals(other.getPayAmt()))
            && (this.getPayDate() == null ? other.getPayDate() == null : this.getPayDate().equals(other.getPayDate()))
            && (this.getPayMode() == null ? other.getPayMode() == null : this.getPayMode().equals(other.getPayMode()))
            && (this.getPayChnl() == null ? other.getPayChnl() == null : this.getPayChnl().equals(other.getPayChnl()))
            && (this.getPayer() == null ? other.getPayer() == null : this.getPayer().equals(other.getPayer()))
            && (this.getPolicyHolder() == null ? other.getPolicyHolder() == null : this.getPolicyHolder().equals(other.getPolicyHolder()))
            && (this.getBeneficiary() == null ? other.getBeneficiary() == null : this.getBeneficiary().equals(other.getBeneficiary()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getTimeStamp() == null ? other.getTimeStamp() == null : this.getTimeStamp().equals(other.getTimeStamp()))
            && (this.getRecStat() == null ? other.getRecStat() == null : this.getRecStat().equals(other.getRecStat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_product
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCustNo() == null) ? 0 : getCustNo().hashCode());
        result = prime * result + ((getProductCd() == null) ? 0 : getProductCd().hashCode());
        result = prime * result + ((getProductTyp() == null) ? 0 : getProductTyp().hashCode());
        result = prime * result + ((getProductNam() == null) ? 0 : getProductNam().hashCode());
        result = prime * result + ((getEffDate() == null) ? 0 : getEffDate().hashCode());
        result = prime * result + ((getExpDate() == null) ? 0 : getExpDate().hashCode());
        result = prime * result + ((getValidSts() == null) ? 0 : getValidSts().hashCode());
        result = prime * result + ((getPayBank() == null) ? 0 : getPayBank().hashCode());
        result = prime * result + ((getPayAc() == null) ? 0 : getPayAc().hashCode());
        result = prime * result + ((getPayYears() == null) ? 0 : getPayYears().hashCode());
        result = prime * result + ((getPayTm() == null) ? 0 : getPayTm().hashCode());
        result = prime * result + ((getPayAmt() == null) ? 0 : getPayAmt().hashCode());
        result = prime * result + ((getPayDate() == null) ? 0 : getPayDate().hashCode());
        result = prime * result + ((getPayMode() == null) ? 0 : getPayMode().hashCode());
        result = prime * result + ((getPayChnl() == null) ? 0 : getPayChnl().hashCode());
        result = prime * result + ((getPayer() == null) ? 0 : getPayer().hashCode());
        result = prime * result + ((getPolicyHolder() == null) ? 0 : getPolicyHolder().hashCode());
        result = prime * result + ((getBeneficiary() == null) ? 0 : getBeneficiary().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getTimeStamp() == null) ? 0 : getTimeStamp().hashCode());
        result = prime * result + ((getRecStat() == null) ? 0 : getRecStat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_product
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", custNo=").append(custNo);
        sb.append(", productCd=").append(productCd);
        sb.append(", productTyp=").append(productTyp);
        sb.append(", productNam=").append(productNam);
        sb.append(", effDate=").append(effDate);
        sb.append(", expDate=").append(expDate);
        sb.append(", validSts=").append(validSts);
        sb.append(", payBank=").append(payBank);
        sb.append(", payAc=").append(payAc);
        sb.append(", payYears=").append(payYears);
        sb.append(", payTm=").append(payTm);
        sb.append(", payAmt=").append(payAmt);
        sb.append(", payDate=").append(payDate);
        sb.append(", payMode=").append(payMode);
        sb.append(", payChnl=").append(payChnl);
        sb.append(", payer=").append(payer);
        sb.append(", policyHolder=").append(policyHolder);
        sb.append(", beneficiary=").append(beneficiary);
        sb.append(", createDate=").append(createDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", recStat=").append(recStat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}