package cn.com.zsyk.crm.ecif.entity;

import java.io.Serializable;
import java.util.Date;

public class EcCustDemand implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.demand_no
     *
     * @mbggenerated
     */
    private String demandNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.cust_no
     *
     * @mbggenerated
     */
    private String custNo;
    private String custNam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.gather_date
     *
     * @mbggenerated
     */
    private String gatherDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.demand_nam
     *
     * @mbggenerated
     */
    private String demandNam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.demand_typ
     *
     * @mbggenerated
     */
    private String demandTyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.demand_phase
     *
     * @mbggenerated
     */
    private String demandPhase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.demand_desc
     *
     * @mbggenerated
     */
    private String demandDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.process_sts
     *
     * @mbggenerated
     */
    private String processSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.principal
     *
     * @mbggenerated
     */
    private String principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.update_date
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.time_stamp
     *
     * @mbggenerated
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_cust_demand.rec_stat
     *
     * @mbggenerated
     */
    private String recStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ec_cust_demand
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.demand_no
     *
     * @return the value of ec_cust_demand.demand_no
     *
     * @mbggenerated
     */
    public String getDemandNo() {
        return demandNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.demand_no
     *
     * @param demandNo the value for ec_cust_demand.demand_no
     *
     * @mbggenerated
     */
    public void setDemandNo(String demandNo) {
        this.demandNo = demandNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.cust_no
     *
     * @return the value of ec_cust_demand.cust_no
     *
     * @mbggenerated
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.cust_no
     *
     * @param custNo the value for ec_cust_demand.cust_no
     *
     * @mbggenerated
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.gather_date
     *
     * @return the value of ec_cust_demand.gather_date
     *
     * @mbggenerated
     */
    public String getGatherDate() {
        return gatherDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.gather_date
     *
     * @param gatherDate the value for ec_cust_demand.gather_date
     *
     * @mbggenerated
     */
    public void setGatherDate(String gatherDate) {
        this.gatherDate = gatherDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.demand_nam
     *
     * @return the value of ec_cust_demand.demand_nam
     *
     * @mbggenerated
     */
    public String getDemandNam() {
        return demandNam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.demand_nam
     *
     * @param demandNam the value for ec_cust_demand.demand_nam
     *
     * @mbggenerated
     */
    public void setDemandNam(String demandNam) {
        this.demandNam = demandNam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.demand_typ
     *
     * @return the value of ec_cust_demand.demand_typ
     *
     * @mbggenerated
     */
    public String getDemandTyp() {
        return demandTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.demand_typ
     *
     * @param demandTyp the value for ec_cust_demand.demand_typ
     *
     * @mbggenerated
     */
    public void setDemandTyp(String demandTyp) {
        this.demandTyp = demandTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.demand_phase
     *
     * @return the value of ec_cust_demand.demand_phase
     *
     * @mbggenerated
     */
    public String getDemandPhase() {
        return demandPhase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.demand_phase
     *
     * @param demandPhase the value for ec_cust_demand.demand_phase
     *
     * @mbggenerated
     */
    public void setDemandPhase(String demandPhase) {
        this.demandPhase = demandPhase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.demand_desc
     *
     * @return the value of ec_cust_demand.demand_desc
     *
     * @mbggenerated
     */
    public String getDemandDesc() {
        return demandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.demand_desc
     *
     * @param demandDesc the value for ec_cust_demand.demand_desc
     *
     * @mbggenerated
     */
    public void setDemandDesc(String demandDesc) {
        this.demandDesc = demandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.process_sts
     *
     * @return the value of ec_cust_demand.process_sts
     *
     * @mbggenerated
     */
    public String getProcessSts() {
        return processSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.process_sts
     *
     * @param processSts the value for ec_cust_demand.process_sts
     *
     * @mbggenerated
     */
    public void setProcessSts(String processSts) {
        this.processSts = processSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.principal
     *
     * @return the value of ec_cust_demand.principal
     *
     * @mbggenerated
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.principal
     *
     * @param principal the value for ec_cust_demand.principal
     *
     * @mbggenerated
     */
    public void setPrincipal(String principal) {
        this.principal = principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.create_date
     *
     * @return the value of ec_cust_demand.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.create_date
     *
     * @param createDate the value for ec_cust_demand.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.create_time
     *
     * @return the value of ec_cust_demand.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.create_time
     *
     * @param createTime the value for ec_cust_demand.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.create_user
     *
     * @return the value of ec_cust_demand.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.create_user
     *
     * @param createUser the value for ec_cust_demand.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.update_date
     *
     * @return the value of ec_cust_demand.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.update_date
     *
     * @param updateDate the value for ec_cust_demand.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.update_time
     *
     * @return the value of ec_cust_demand.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.update_time
     *
     * @param updateTime the value for ec_cust_demand.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.update_user
     *
     * @return the value of ec_cust_demand.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.update_user
     *
     * @param updateUser the value for ec_cust_demand.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.time_stamp
     *
     * @return the value of ec_cust_demand.time_stamp
     *
     * @mbggenerated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.time_stamp
     *
     * @param timeStamp the value for ec_cust_demand.time_stamp
     *
     * @mbggenerated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_cust_demand.rec_stat
     *
     * @return the value of ec_cust_demand.rec_stat
     *
     * @mbggenerated
     */
    public String getRecStat() {
        return recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_cust_demand.rec_stat
     *
     * @param recStat the value for ec_cust_demand.rec_stat
     *
     * @mbggenerated
     */
    public void setRecStat(String recStat) {
        this.recStat = recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_demand
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EcCustDemand other = (EcCustDemand) that;
        return (this.getDemandNo() == null ? other.getDemandNo() == null : this.getDemandNo().equals(other.getDemandNo()))
            && (this.getCustNo() == null ? other.getCustNo() == null : this.getCustNo().equals(other.getCustNo()))
            && (this.getGatherDate() == null ? other.getGatherDate() == null : this.getGatherDate().equals(other.getGatherDate()))
            && (this.getDemandNam() == null ? other.getDemandNam() == null : this.getDemandNam().equals(other.getDemandNam()))
            && (this.getDemandTyp() == null ? other.getDemandTyp() == null : this.getDemandTyp().equals(other.getDemandTyp()))
            && (this.getDemandPhase() == null ? other.getDemandPhase() == null : this.getDemandPhase().equals(other.getDemandPhase()))
            && (this.getDemandDesc() == null ? other.getDemandDesc() == null : this.getDemandDesc().equals(other.getDemandDesc()))
            && (this.getProcessSts() == null ? other.getProcessSts() == null : this.getProcessSts().equals(other.getProcessSts()))
            && (this.getPrincipal() == null ? other.getPrincipal() == null : this.getPrincipal().equals(other.getPrincipal()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getTimeStamp() == null ? other.getTimeStamp() == null : this.getTimeStamp().equals(other.getTimeStamp()))
            && (this.getRecStat() == null ? other.getRecStat() == null : this.getRecStat().equals(other.getRecStat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_demand
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDemandNo() == null) ? 0 : getDemandNo().hashCode());
        result = prime * result + ((getCustNo() == null) ? 0 : getCustNo().hashCode());
        result = prime * result + ((getGatherDate() == null) ? 0 : getGatherDate().hashCode());
        result = prime * result + ((getDemandNam() == null) ? 0 : getDemandNam().hashCode());
        result = prime * result + ((getDemandTyp() == null) ? 0 : getDemandTyp().hashCode());
        result = prime * result + ((getDemandPhase() == null) ? 0 : getDemandPhase().hashCode());
        result = prime * result + ((getDemandDesc() == null) ? 0 : getDemandDesc().hashCode());
        result = prime * result + ((getProcessSts() == null) ? 0 : getProcessSts().hashCode());
        result = prime * result + ((getPrincipal() == null) ? 0 : getPrincipal().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getTimeStamp() == null) ? 0 : getTimeStamp().hashCode());
        result = prime * result + ((getRecStat() == null) ? 0 : getRecStat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_demand
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", demandNo=").append(demandNo);
        sb.append(", custNo=").append(custNo);
        sb.append(", gatherDate=").append(gatherDate);
        sb.append(", demandNam=").append(demandNam);
        sb.append(", demandTyp=").append(demandTyp);
        sb.append(", demandPhase=").append(demandPhase);
        sb.append(", demandDesc=").append(demandDesc);
        sb.append(", processSts=").append(processSts);
        sb.append(", principal=").append(principal);
        sb.append(", createDate=").append(createDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", recStat=").append(recStat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

	
	/**
	 * Desc: 
	 * @return 
	 * @author
	 */
	public String getCustNam() {
		return custNam;
	}

	
	/**
	 * Desc: 
	 * custNam
	 * @author
	 */
	public void setCustNam(String custNam) {
		this.custNam = custNam;
	}
    
}