package cn.com.zsyk.crm.ecif.entity;

import java.io.Serializable;
import java.util.Date;

public class EcDiffCust implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.task_id
     *
     * @mbggenerated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.source_cust_no
     *
     * @mbggenerated
     */
    private String sourceCustNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.target_cust_no
     *
     * @mbggenerated
     */
    private String targetCustNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.mark_user
     *
     * @mbggenerated
     */
    private String markUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.mark_reason
     *
     * @mbggenerated
     */
    private String markReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.mark_time
     *
     * @mbggenerated
     */
    private Date markTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.mark_conclusion
     *
     * @mbggenerated
     */
    private String markConclusion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.update_date
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.time_stamp
     *
     * @mbggenerated
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_diff_cust.rec_stat
     *
     * @mbggenerated
     */
    private String recStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ec_diff_cust
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.task_id
     *
     * @return the value of ec_diff_cust.task_id
     *
     * @mbggenerated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.task_id
     *
     * @param taskId the value for ec_diff_cust.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.source_cust_no
     *
     * @return the value of ec_diff_cust.source_cust_no
     *
     * @mbggenerated
     */
    public String getSourceCustNo() {
        return sourceCustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.source_cust_no
     *
     * @param sourceCustNo the value for ec_diff_cust.source_cust_no
     *
     * @mbggenerated
     */
    public void setSourceCustNo(String sourceCustNo) {
        this.sourceCustNo = sourceCustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.target_cust_no
     *
     * @return the value of ec_diff_cust.target_cust_no
     *
     * @mbggenerated
     */
    public String getTargetCustNo() {
        return targetCustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.target_cust_no
     *
     * @param targetCustNo the value for ec_diff_cust.target_cust_no
     *
     * @mbggenerated
     */
    public void setTargetCustNo(String targetCustNo) {
        this.targetCustNo = targetCustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.mark_user
     *
     * @return the value of ec_diff_cust.mark_user
     *
     * @mbggenerated
     */
    public String getMarkUser() {
        return markUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.mark_user
     *
     * @param markUser the value for ec_diff_cust.mark_user
     *
     * @mbggenerated
     */
    public void setMarkUser(String markUser) {
        this.markUser = markUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.mark_reason
     *
     * @return the value of ec_diff_cust.mark_reason
     *
     * @mbggenerated
     */
    public String getMarkReason() {
        return markReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.mark_reason
     *
     * @param markReason the value for ec_diff_cust.mark_reason
     *
     * @mbggenerated
     */
    public void setMarkReason(String markReason) {
        this.markReason = markReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.mark_time
     *
     * @return the value of ec_diff_cust.mark_time
     *
     * @mbggenerated
     */
    public Date getMarkTime() {
        return markTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.mark_time
     *
     * @param markTime the value for ec_diff_cust.mark_time
     *
     * @mbggenerated
     */
    public void setMarkTime(Date markTime) {
        this.markTime = markTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.mark_conclusion
     *
     * @return the value of ec_diff_cust.mark_conclusion
     *
     * @mbggenerated
     */
    public String getMarkConclusion() {
        return markConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.mark_conclusion
     *
     * @param markConclusion the value for ec_diff_cust.mark_conclusion
     *
     * @mbggenerated
     */
    public void setMarkConclusion(String markConclusion) {
        this.markConclusion = markConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.create_date
     *
     * @return the value of ec_diff_cust.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.create_date
     *
     * @param createDate the value for ec_diff_cust.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.create_time
     *
     * @return the value of ec_diff_cust.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.create_time
     *
     * @param createTime the value for ec_diff_cust.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.create_user
     *
     * @return the value of ec_diff_cust.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.create_user
     *
     * @param createUser the value for ec_diff_cust.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.update_date
     *
     * @return the value of ec_diff_cust.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.update_date
     *
     * @param updateDate the value for ec_diff_cust.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.update_time
     *
     * @return the value of ec_diff_cust.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.update_time
     *
     * @param updateTime the value for ec_diff_cust.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.update_user
     *
     * @return the value of ec_diff_cust.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.update_user
     *
     * @param updateUser the value for ec_diff_cust.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.time_stamp
     *
     * @return the value of ec_diff_cust.time_stamp
     *
     * @mbggenerated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.time_stamp
     *
     * @param timeStamp the value for ec_diff_cust.time_stamp
     *
     * @mbggenerated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_diff_cust.rec_stat
     *
     * @return the value of ec_diff_cust.rec_stat
     *
     * @mbggenerated
     */
    public String getRecStat() {
        return recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_diff_cust.rec_stat
     *
     * @param recStat the value for ec_diff_cust.rec_stat
     *
     * @mbggenerated
     */
    public void setRecStat(String recStat) {
        this.recStat = recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_diff_cust
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EcDiffCust other = (EcDiffCust) that;
        return (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
            && (this.getSourceCustNo() == null ? other.getSourceCustNo() == null : this.getSourceCustNo().equals(other.getSourceCustNo()))
            && (this.getTargetCustNo() == null ? other.getTargetCustNo() == null : this.getTargetCustNo().equals(other.getTargetCustNo()))
            && (this.getMarkUser() == null ? other.getMarkUser() == null : this.getMarkUser().equals(other.getMarkUser()))
            && (this.getMarkReason() == null ? other.getMarkReason() == null : this.getMarkReason().equals(other.getMarkReason()))
            && (this.getMarkTime() == null ? other.getMarkTime() == null : this.getMarkTime().equals(other.getMarkTime()))
            && (this.getMarkConclusion() == null ? other.getMarkConclusion() == null : this.getMarkConclusion().equals(other.getMarkConclusion()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getTimeStamp() == null ? other.getTimeStamp() == null : this.getTimeStamp().equals(other.getTimeStamp()))
            && (this.getRecStat() == null ? other.getRecStat() == null : this.getRecStat().equals(other.getRecStat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_diff_cust
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
        result = prime * result + ((getSourceCustNo() == null) ? 0 : getSourceCustNo().hashCode());
        result = prime * result + ((getTargetCustNo() == null) ? 0 : getTargetCustNo().hashCode());
        result = prime * result + ((getMarkUser() == null) ? 0 : getMarkUser().hashCode());
        result = prime * result + ((getMarkReason() == null) ? 0 : getMarkReason().hashCode());
        result = prime * result + ((getMarkTime() == null) ? 0 : getMarkTime().hashCode());
        result = prime * result + ((getMarkConclusion() == null) ? 0 : getMarkConclusion().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getTimeStamp() == null) ? 0 : getTimeStamp().hashCode());
        result = prime * result + ((getRecStat() == null) ? 0 : getRecStat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_diff_cust
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", taskId=").append(taskId);
        sb.append(", sourceCustNo=").append(sourceCustNo);
        sb.append(", targetCustNo=").append(targetCustNo);
        sb.append(", markUser=").append(markUser);
        sb.append(", markReason=").append(markReason);
        sb.append(", markTime=").append(markTime);
        sb.append(", markConclusion=").append(markConclusion);
        sb.append(", createDate=").append(createDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", recStat=").append(recStat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}