package cn.com.zsyk.crm.ecif.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class EcFinacePay implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.cust_no
     *
     * @mbggenerated
     */
    private String custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.policy_no
     *
     * @mbggenerated
     */
    private String policyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.pay_date
     *
     * @mbggenerated
     */
    private String payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.pay_chnl
     *
     * @mbggenerated
     */
    private String payChnl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.pay_bank
     *
     * @mbggenerated
     */
    private String payBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.pay_account
     *
     * @mbggenerated
     */
    private String payAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.pay_ac_last_four
     *
     * @mbggenerated
     */
    private String payAcLastFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.pay_years
     *
     * @mbggenerated
     */
    private Integer payYears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.pay_tm
     *
     * @mbggenerated
     */
    private Integer payTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.pay_trequency
     *
     * @mbggenerated
     */
    private Integer payTrequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.pay_amt
     *
     * @mbggenerated
     */
    private BigDecimal payAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.payable_date
     *
     * @mbggenerated
     */
    private String payableDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.pay_mode
     *
     * @mbggenerated
     */
    private String payMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.payer
     *
     * @mbggenerated
     */
    private String payer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.applicant
     *
     * @mbggenerated
     */
    private String applicant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.update_date
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.time_stamp
     *
     * @mbggenerated
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_finace_pay.rec_stat
     *
     * @mbggenerated
     */
    private String recStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ec_finace_pay
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.cust_no
     *
     * @return the value of ec_finace_pay.cust_no
     *
     * @mbggenerated
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.cust_no
     *
     * @param custNo the value for ec_finace_pay.cust_no
     *
     * @mbggenerated
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.policy_no
     *
     * @return the value of ec_finace_pay.policy_no
     *
     * @mbggenerated
     */
    public String getPolicyNo() {
        return policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.policy_no
     *
     * @param policyNo the value for ec_finace_pay.policy_no
     *
     * @mbggenerated
     */
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.pay_date
     *
     * @return the value of ec_finace_pay.pay_date
     *
     * @mbggenerated
     */
    public String getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.pay_date
     *
     * @param payDate the value for ec_finace_pay.pay_date
     *
     * @mbggenerated
     */
    public void setPayDate(String payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.pay_chnl
     *
     * @return the value of ec_finace_pay.pay_chnl
     *
     * @mbggenerated
     */
    public String getPayChnl() {
        return payChnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.pay_chnl
     *
     * @param payChnl the value for ec_finace_pay.pay_chnl
     *
     * @mbggenerated
     */
    public void setPayChnl(String payChnl) {
        this.payChnl = payChnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.pay_bank
     *
     * @return the value of ec_finace_pay.pay_bank
     *
     * @mbggenerated
     */
    public String getPayBank() {
        return payBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.pay_bank
     *
     * @param payBank the value for ec_finace_pay.pay_bank
     *
     * @mbggenerated
     */
    public void setPayBank(String payBank) {
        this.payBank = payBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.pay_account
     *
     * @return the value of ec_finace_pay.pay_account
     *
     * @mbggenerated
     */
    public String getPayAccount() {
        return payAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.pay_account
     *
     * @param payAccount the value for ec_finace_pay.pay_account
     *
     * @mbggenerated
     */
    public void setPayAccount(String payAccount) {
        this.payAccount = payAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.pay_ac_last_four
     *
     * @return the value of ec_finace_pay.pay_ac_last_four
     *
     * @mbggenerated
     */
    public String getPayAcLastFour() {
        return payAcLastFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.pay_ac_last_four
     *
     * @param payAcLastFour the value for ec_finace_pay.pay_ac_last_four
     *
     * @mbggenerated
     */
    public void setPayAcLastFour(String payAcLastFour) {
        this.payAcLastFour = payAcLastFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.pay_years
     *
     * @return the value of ec_finace_pay.pay_years
     *
     * @mbggenerated
     */
    public Integer getPayYears() {
        return payYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.pay_years
     *
     * @param payYears the value for ec_finace_pay.pay_years
     *
     * @mbggenerated
     */
    public void setPayYears(Integer payYears) {
        this.payYears = payYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.pay_tm
     *
     * @return the value of ec_finace_pay.pay_tm
     *
     * @mbggenerated
     */
    public Integer getPayTm() {
        return payTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.pay_tm
     *
     * @param payTm the value for ec_finace_pay.pay_tm
     *
     * @mbggenerated
     */
    public void setPayTm(Integer payTm) {
        this.payTm = payTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.pay_trequency
     *
     * @return the value of ec_finace_pay.pay_trequency
     *
     * @mbggenerated
     */
    public Integer getPayTrequency() {
        return payTrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.pay_trequency
     *
     * @param payTrequency the value for ec_finace_pay.pay_trequency
     *
     * @mbggenerated
     */
    public void setPayTrequency(Integer payTrequency) {
        this.payTrequency = payTrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.pay_amt
     *
     * @return the value of ec_finace_pay.pay_amt
     *
     * @mbggenerated
     */
    public BigDecimal getPayAmt() {
        return payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.pay_amt
     *
     * @param payAmt the value for ec_finace_pay.pay_amt
     *
     * @mbggenerated
     */
    public void setPayAmt(BigDecimal payAmt) {
        this.payAmt = payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.payable_date
     *
     * @return the value of ec_finace_pay.payable_date
     *
     * @mbggenerated
     */
    public String getPayableDate() {
        return payableDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.payable_date
     *
     * @param payableDate the value for ec_finace_pay.payable_date
     *
     * @mbggenerated
     */
    public void setPayableDate(String payableDate) {
        this.payableDate = payableDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.pay_mode
     *
     * @return the value of ec_finace_pay.pay_mode
     *
     * @mbggenerated
     */
    public String getPayMode() {
        return payMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.pay_mode
     *
     * @param payMode the value for ec_finace_pay.pay_mode
     *
     * @mbggenerated
     */
    public void setPayMode(String payMode) {
        this.payMode = payMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.payer
     *
     * @return the value of ec_finace_pay.payer
     *
     * @mbggenerated
     */
    public String getPayer() {
        return payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.payer
     *
     * @param payer the value for ec_finace_pay.payer
     *
     * @mbggenerated
     */
    public void setPayer(String payer) {
        this.payer = payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.applicant
     *
     * @return the value of ec_finace_pay.applicant
     *
     * @mbggenerated
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.applicant
     *
     * @param applicant the value for ec_finace_pay.applicant
     *
     * @mbggenerated
     */
    public void setApplicant(String applicant) {
        this.applicant = applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.create_date
     *
     * @return the value of ec_finace_pay.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.create_date
     *
     * @param createDate the value for ec_finace_pay.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.create_time
     *
     * @return the value of ec_finace_pay.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.create_time
     *
     * @param createTime the value for ec_finace_pay.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.create_user
     *
     * @return the value of ec_finace_pay.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.create_user
     *
     * @param createUser the value for ec_finace_pay.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.update_date
     *
     * @return the value of ec_finace_pay.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.update_date
     *
     * @param updateDate the value for ec_finace_pay.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.update_time
     *
     * @return the value of ec_finace_pay.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.update_time
     *
     * @param updateTime the value for ec_finace_pay.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.update_user
     *
     * @return the value of ec_finace_pay.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.update_user
     *
     * @param updateUser the value for ec_finace_pay.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.time_stamp
     *
     * @return the value of ec_finace_pay.time_stamp
     *
     * @mbggenerated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.time_stamp
     *
     * @param timeStamp the value for ec_finace_pay.time_stamp
     *
     * @mbggenerated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_finace_pay.rec_stat
     *
     * @return the value of ec_finace_pay.rec_stat
     *
     * @mbggenerated
     */
    public String getRecStat() {
        return recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_finace_pay.rec_stat
     *
     * @param recStat the value for ec_finace_pay.rec_stat
     *
     * @mbggenerated
     */
    public void setRecStat(String recStat) {
        this.recStat = recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_finace_pay
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EcFinacePay other = (EcFinacePay) that;
        return (this.getCustNo() == null ? other.getCustNo() == null : this.getCustNo().equals(other.getCustNo()))
            && (this.getPolicyNo() == null ? other.getPolicyNo() == null : this.getPolicyNo().equals(other.getPolicyNo()))
            && (this.getPayDate() == null ? other.getPayDate() == null : this.getPayDate().equals(other.getPayDate()))
            && (this.getPayChnl() == null ? other.getPayChnl() == null : this.getPayChnl().equals(other.getPayChnl()))
            && (this.getPayBank() == null ? other.getPayBank() == null : this.getPayBank().equals(other.getPayBank()))
            && (this.getPayAccount() == null ? other.getPayAccount() == null : this.getPayAccount().equals(other.getPayAccount()))
            && (this.getPayAcLastFour() == null ? other.getPayAcLastFour() == null : this.getPayAcLastFour().equals(other.getPayAcLastFour()))
            && (this.getPayYears() == null ? other.getPayYears() == null : this.getPayYears().equals(other.getPayYears()))
            && (this.getPayTm() == null ? other.getPayTm() == null : this.getPayTm().equals(other.getPayTm()))
            && (this.getPayTrequency() == null ? other.getPayTrequency() == null : this.getPayTrequency().equals(other.getPayTrequency()))
            && (this.getPayAmt() == null ? other.getPayAmt() == null : this.getPayAmt().equals(other.getPayAmt()))
            && (this.getPayableDate() == null ? other.getPayableDate() == null : this.getPayableDate().equals(other.getPayableDate()))
            && (this.getPayMode() == null ? other.getPayMode() == null : this.getPayMode().equals(other.getPayMode()))
            && (this.getPayer() == null ? other.getPayer() == null : this.getPayer().equals(other.getPayer()))
            && (this.getApplicant() == null ? other.getApplicant() == null : this.getApplicant().equals(other.getApplicant()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getTimeStamp() == null ? other.getTimeStamp() == null : this.getTimeStamp().equals(other.getTimeStamp()))
            && (this.getRecStat() == null ? other.getRecStat() == null : this.getRecStat().equals(other.getRecStat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_finace_pay
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCustNo() == null) ? 0 : getCustNo().hashCode());
        result = prime * result + ((getPolicyNo() == null) ? 0 : getPolicyNo().hashCode());
        result = prime * result + ((getPayDate() == null) ? 0 : getPayDate().hashCode());
        result = prime * result + ((getPayChnl() == null) ? 0 : getPayChnl().hashCode());
        result = prime * result + ((getPayBank() == null) ? 0 : getPayBank().hashCode());
        result = prime * result + ((getPayAccount() == null) ? 0 : getPayAccount().hashCode());
        result = prime * result + ((getPayAcLastFour() == null) ? 0 : getPayAcLastFour().hashCode());
        result = prime * result + ((getPayYears() == null) ? 0 : getPayYears().hashCode());
        result = prime * result + ((getPayTm() == null) ? 0 : getPayTm().hashCode());
        result = prime * result + ((getPayTrequency() == null) ? 0 : getPayTrequency().hashCode());
        result = prime * result + ((getPayAmt() == null) ? 0 : getPayAmt().hashCode());
        result = prime * result + ((getPayableDate() == null) ? 0 : getPayableDate().hashCode());
        result = prime * result + ((getPayMode() == null) ? 0 : getPayMode().hashCode());
        result = prime * result + ((getPayer() == null) ? 0 : getPayer().hashCode());
        result = prime * result + ((getApplicant() == null) ? 0 : getApplicant().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getTimeStamp() == null) ? 0 : getTimeStamp().hashCode());
        result = prime * result + ((getRecStat() == null) ? 0 : getRecStat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_finace_pay
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", custNo=").append(custNo);
        sb.append(", policyNo=").append(policyNo);
        sb.append(", payDate=").append(payDate);
        sb.append(", payChnl=").append(payChnl);
        sb.append(", payBank=").append(payBank);
        sb.append(", payAccount=").append(payAccount);
        sb.append(", payAcLastFour=").append(payAcLastFour);
        sb.append(", payYears=").append(payYears);
        sb.append(", payTm=").append(payTm);
        sb.append(", payTrequency=").append(payTrequency);
        sb.append(", payAmt=").append(payAmt);
        sb.append(", payableDate=").append(payableDate);
        sb.append(", payMode=").append(payMode);
        sb.append(", payer=").append(payer);
        sb.append(", applicant=").append(applicant);
        sb.append(", createDate=").append(createDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", recStat=").append(recStat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}