package cn.com.zsyk.crm.ecif.entity;

import java.io.Serializable;
import java.util.Date;

public class EcMergeSplitTrace implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.trace_id
     *
     * @mbggenerated
     */
    private Integer traceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.task_id
     *
     * @mbggenerated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.merge_split_action
     *
     * @mbggenerated
     */
    private String mergeSplitAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.deal_user
     *
     * @mbggenerated
     */
    private String dealUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.deal_time
     *
     * @mbggenerated
     */
    private Date dealTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.deal_conclusion
     *
     * @mbggenerated
     */
    private String dealConclusion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.deal_opinion
     *
     * @mbggenerated
     */
    private String dealOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.update_date
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.time_stamp
     *
     * @mbggenerated
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_merge_split_trace.rec_stat
     *
     * @mbggenerated
     */
    private String recStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ec_merge_split_trace
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.trace_id
     *
     * @return the value of ec_merge_split_trace.trace_id
     *
     * @mbggenerated
     */
    public Integer getTraceId() {
        return traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.trace_id
     *
     * @param traceId the value for ec_merge_split_trace.trace_id
     *
     * @mbggenerated
     */
    public void setTraceId(Integer traceId) {
        this.traceId = traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.task_id
     *
     * @return the value of ec_merge_split_trace.task_id
     *
     * @mbggenerated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.task_id
     *
     * @param taskId the value for ec_merge_split_trace.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.merge_split_action
     *
     * @return the value of ec_merge_split_trace.merge_split_action
     *
     * @mbggenerated
     */
    public String getMergeSplitAction() {
        return mergeSplitAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.merge_split_action
     *
     * @param mergeSplitAction the value for ec_merge_split_trace.merge_split_action
     *
     * @mbggenerated
     */
    public void setMergeSplitAction(String mergeSplitAction) {
        this.mergeSplitAction = mergeSplitAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.deal_user
     *
     * @return the value of ec_merge_split_trace.deal_user
     *
     * @mbggenerated
     */
    public String getDealUser() {
        return dealUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.deal_user
     *
     * @param dealUser the value for ec_merge_split_trace.deal_user
     *
     * @mbggenerated
     */
    public void setDealUser(String dealUser) {
        this.dealUser = dealUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.deal_time
     *
     * @return the value of ec_merge_split_trace.deal_time
     *
     * @mbggenerated
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.deal_time
     *
     * @param dealTime the value for ec_merge_split_trace.deal_time
     *
     * @mbggenerated
     */
    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.deal_conclusion
     *
     * @return the value of ec_merge_split_trace.deal_conclusion
     *
     * @mbggenerated
     */
    public String getDealConclusion() {
        return dealConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.deal_conclusion
     *
     * @param dealConclusion the value for ec_merge_split_trace.deal_conclusion
     *
     * @mbggenerated
     */
    public void setDealConclusion(String dealConclusion) {
        this.dealConclusion = dealConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.deal_opinion
     *
     * @return the value of ec_merge_split_trace.deal_opinion
     *
     * @mbggenerated
     */
    public String getDealOpinion() {
        return dealOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.deal_opinion
     *
     * @param dealOpinion the value for ec_merge_split_trace.deal_opinion
     *
     * @mbggenerated
     */
    public void setDealOpinion(String dealOpinion) {
        this.dealOpinion = dealOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.create_date
     *
     * @return the value of ec_merge_split_trace.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.create_date
     *
     * @param createDate the value for ec_merge_split_trace.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.create_time
     *
     * @return the value of ec_merge_split_trace.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.create_time
     *
     * @param createTime the value for ec_merge_split_trace.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.create_user
     *
     * @return the value of ec_merge_split_trace.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.create_user
     *
     * @param createUser the value for ec_merge_split_trace.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.update_date
     *
     * @return the value of ec_merge_split_trace.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.update_date
     *
     * @param updateDate the value for ec_merge_split_trace.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.update_time
     *
     * @return the value of ec_merge_split_trace.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.update_time
     *
     * @param updateTime the value for ec_merge_split_trace.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.update_user
     *
     * @return the value of ec_merge_split_trace.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.update_user
     *
     * @param updateUser the value for ec_merge_split_trace.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.time_stamp
     *
     * @return the value of ec_merge_split_trace.time_stamp
     *
     * @mbggenerated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.time_stamp
     *
     * @param timeStamp the value for ec_merge_split_trace.time_stamp
     *
     * @mbggenerated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_merge_split_trace.rec_stat
     *
     * @return the value of ec_merge_split_trace.rec_stat
     *
     * @mbggenerated
     */
    public String getRecStat() {
        return recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_merge_split_trace.rec_stat
     *
     * @param recStat the value for ec_merge_split_trace.rec_stat
     *
     * @mbggenerated
     */
    public void setRecStat(String recStat) {
        this.recStat = recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_merge_split_trace
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EcMergeSplitTrace other = (EcMergeSplitTrace) that;
        return (this.getTraceId() == null ? other.getTraceId() == null : this.getTraceId().equals(other.getTraceId()))
            && (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
            && (this.getMergeSplitAction() == null ? other.getMergeSplitAction() == null : this.getMergeSplitAction().equals(other.getMergeSplitAction()))
            && (this.getDealUser() == null ? other.getDealUser() == null : this.getDealUser().equals(other.getDealUser()))
            && (this.getDealTime() == null ? other.getDealTime() == null : this.getDealTime().equals(other.getDealTime()))
            && (this.getDealConclusion() == null ? other.getDealConclusion() == null : this.getDealConclusion().equals(other.getDealConclusion()))
            && (this.getDealOpinion() == null ? other.getDealOpinion() == null : this.getDealOpinion().equals(other.getDealOpinion()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getTimeStamp() == null ? other.getTimeStamp() == null : this.getTimeStamp().equals(other.getTimeStamp()))
            && (this.getRecStat() == null ? other.getRecStat() == null : this.getRecStat().equals(other.getRecStat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_merge_split_trace
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTraceId() == null) ? 0 : getTraceId().hashCode());
        result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
        result = prime * result + ((getMergeSplitAction() == null) ? 0 : getMergeSplitAction().hashCode());
        result = prime * result + ((getDealUser() == null) ? 0 : getDealUser().hashCode());
        result = prime * result + ((getDealTime() == null) ? 0 : getDealTime().hashCode());
        result = prime * result + ((getDealConclusion() == null) ? 0 : getDealConclusion().hashCode());
        result = prime * result + ((getDealOpinion() == null) ? 0 : getDealOpinion().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getTimeStamp() == null) ? 0 : getTimeStamp().hashCode());
        result = prime * result + ((getRecStat() == null) ? 0 : getRecStat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_merge_split_trace
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", traceId=").append(traceId);
        sb.append(", taskId=").append(taskId);
        sb.append(", mergeSplitAction=").append(mergeSplitAction);
        sb.append(", dealUser=").append(dealUser);
        sb.append(", dealTime=").append(dealTime);
        sb.append(", dealConclusion=").append(dealConclusion);
        sb.append(", dealOpinion=").append(dealOpinion);
        sb.append(", createDate=").append(createDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", recStat=").append(recStat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}