package cn.com.zsyk.crm.ecif.entity;

import java.io.Serializable;

public class EcOurnalTag implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_OURNAL_TAG.OURNAL_ID
     *
     * @mbggenerated
     */
    private String ournalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_OURNAL_TAG.OURNAL_NAME
     *
     * @mbggenerated
     */
    private String ournalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_OURNAL_TAG.START_TIME
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_OURNAL_TAG.END_TIME
     *
     * @mbggenerated
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_OURNAL_TAG.CREATE_DATE
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_OURNAL_TAG.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_OURNAL_TAG.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_OURNAL_TAG.UPDATE_DATE
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_OURNAL_TAG.UPDATE_TIME
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_OURNAL_TAG.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_OURNAL_TAG.TIME_STAMP
     *
     * @mbggenerated
     */
    private String timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EC_OURNAL_TAG.REC_STAT
     *
     * @mbggenerated
     */
    private String recStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EC_OURNAL_TAG
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_OURNAL_TAG.OURNAL_ID
     *
     * @return the value of EC_OURNAL_TAG.OURNAL_ID
     *
     * @mbggenerated
     */
    public String getOurnalId() {
        return ournalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_OURNAL_TAG.OURNAL_ID
     *
     * @param ournalId the value for EC_OURNAL_TAG.OURNAL_ID
     *
     * @mbggenerated
     */
    public void setOurnalId(String ournalId) {
        this.ournalId = ournalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_OURNAL_TAG.OURNAL_NAME
     *
     * @return the value of EC_OURNAL_TAG.OURNAL_NAME
     *
     * @mbggenerated
     */
    public String getOurnalName() {
        return ournalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_OURNAL_TAG.OURNAL_NAME
     *
     * @param ournalName the value for EC_OURNAL_TAG.OURNAL_NAME
     *
     * @mbggenerated
     */
    public void setOurnalName(String ournalName) {
        this.ournalName = ournalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_OURNAL_TAG.START_TIME
     *
     * @return the value of EC_OURNAL_TAG.START_TIME
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_OURNAL_TAG.START_TIME
     *
     * @param startTime the value for EC_OURNAL_TAG.START_TIME
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_OURNAL_TAG.END_TIME
     *
     * @return the value of EC_OURNAL_TAG.END_TIME
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_OURNAL_TAG.END_TIME
     *
     * @param endTime the value for EC_OURNAL_TAG.END_TIME
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_OURNAL_TAG.CREATE_DATE
     *
     * @return the value of EC_OURNAL_TAG.CREATE_DATE
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_OURNAL_TAG.CREATE_DATE
     *
     * @param createDate the value for EC_OURNAL_TAG.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_OURNAL_TAG.CREATE_TIME
     *
     * @return the value of EC_OURNAL_TAG.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_OURNAL_TAG.CREATE_TIME
     *
     * @param createTime the value for EC_OURNAL_TAG.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_OURNAL_TAG.CREATE_USER
     *
     * @return the value of EC_OURNAL_TAG.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_OURNAL_TAG.CREATE_USER
     *
     * @param createUser the value for EC_OURNAL_TAG.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_OURNAL_TAG.UPDATE_DATE
     *
     * @return the value of EC_OURNAL_TAG.UPDATE_DATE
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_OURNAL_TAG.UPDATE_DATE
     *
     * @param updateDate the value for EC_OURNAL_TAG.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_OURNAL_TAG.UPDATE_TIME
     *
     * @return the value of EC_OURNAL_TAG.UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_OURNAL_TAG.UPDATE_TIME
     *
     * @param updateTime the value for EC_OURNAL_TAG.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_OURNAL_TAG.UPDATE_USER
     *
     * @return the value of EC_OURNAL_TAG.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_OURNAL_TAG.UPDATE_USER
     *
     * @param updateUser the value for EC_OURNAL_TAG.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_OURNAL_TAG.TIME_STAMP
     *
     * @return the value of EC_OURNAL_TAG.TIME_STAMP
     *
     * @mbggenerated
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_OURNAL_TAG.TIME_STAMP
     *
     * @param timeStamp the value for EC_OURNAL_TAG.TIME_STAMP
     *
     * @mbggenerated
     */
    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EC_OURNAL_TAG.REC_STAT
     *
     * @return the value of EC_OURNAL_TAG.REC_STAT
     *
     * @mbggenerated
     */
    public String getRecStat() {
        return recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EC_OURNAL_TAG.REC_STAT
     *
     * @param recStat the value for EC_OURNAL_TAG.REC_STAT
     *
     * @mbggenerated
     */
    public void setRecStat(String recStat) {
        this.recStat = recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_OURNAL_TAG
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EcOurnalTag other = (EcOurnalTag) that;
        return (this.getOurnalId() == null ? other.getOurnalId() == null : this.getOurnalId().equals(other.getOurnalId()))
            && (this.getOurnalName() == null ? other.getOurnalName() == null : this.getOurnalName().equals(other.getOurnalName()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getTimeStamp() == null ? other.getTimeStamp() == null : this.getTimeStamp().equals(other.getTimeStamp()))
            && (this.getRecStat() == null ? other.getRecStat() == null : this.getRecStat().equals(other.getRecStat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_OURNAL_TAG
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOurnalId() == null) ? 0 : getOurnalId().hashCode());
        result = prime * result + ((getOurnalName() == null) ? 0 : getOurnalName().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getTimeStamp() == null) ? 0 : getTimeStamp().hashCode());
        result = prime * result + ((getRecStat() == null) ? 0 : getRecStat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EC_OURNAL_TAG
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ournalId=").append(ournalId);
        sb.append(", ournalName=").append(ournalName);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", createDate=").append(createDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", recStat=").append(recStat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}