package cn.com.zsyk.crm.ecif.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class EcSimTask implements Serializable {

    private String userName;
    private String approveUserName;
    private String splitUserName;
    private String splitApproveUserName;

    public String getApproveUserName() {
        return approveUserName;
    }

    public void setApproveUserName(String approveUserName) {
        this.approveUserName = approveUserName;
    }

    public String getSplitUserName() {
        return splitUserName;
    }

    public void setSplitUserName(String splitUserName) {
        this.splitUserName = splitUserName;
    }

    public String getSplitApproveUserName() {
        return splitApproveUserName;
    }

    public void setSplitApproveUserName(String splitApproveUserName) {
        this.splitApproveUserName = splitApproveUserName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    private String certTyp;
    private String certNo;

    public String getCertTyp() {
        return certTyp;
    }

    public void setCertTyp(String certTyp) {
        this.certTyp = certTyp;
    }

    public String getCertNo() {
        return certNo;
    }

    public void setCertNo(String certNo) {
        this.certNo = certNo;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.task_id
     *
     * @mbggenerated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.rule_id
     *
     * @mbggenerated
     */
    private Integer ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.similar_percent
     *
     * @mbggenerated
     */
    private String similarPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.task_create_time
     *
     * @mbggenerated
     */
    private Date taskCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.task_state
     *
     * @mbggenerated
     */
    private String taskState;
    private List<String> taskStates;

	public List<String> getTaskStates() {
		return taskStates;
	}

	public void setTaskStates(List<String> taskStates) {
		this.taskStates = taskStates;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.deal_user
     *
     * @mbggenerated
     */
    private String dealUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.approve_user
     *
     * @mbggenerated
     */
    private String approveUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.split_deal_user
     *
     * @mbggenerated
     */
    private String splitDealUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.split_approve_user
     *
     * @mbggenerated
     */
    private String splitApproveUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.update_date
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.time_stamp
     *
     * @mbggenerated
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_sim_task.rec_stat
     *
     * @mbggenerated
     */
    private String recStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ec_sim_task
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.task_id
     *
     * @return the value of ec_sim_task.task_id
     *
     * @mbggenerated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.task_id
     *
     * @param taskId the value for ec_sim_task.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.rule_id
     *
     * @return the value of ec_sim_task.rule_id
     *
     * @mbggenerated
     */
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.rule_id
     *
     * @param ruleId the value for ec_sim_task.rule_id
     *
     * @mbggenerated
     */
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.similar_percent
     *
     * @return the value of ec_sim_task.similar_percent
     *
     * @mbggenerated
     */
    public String getSimilarPercent() {
        return similarPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.similar_percent
     *
     * @param similarPercent the value for ec_sim_task.similar_percent
     *
     * @mbggenerated
     */
    public void setSimilarPercent(String similarPercent) {
        this.similarPercent = similarPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.task_create_time
     *
     * @return the value of ec_sim_task.task_create_time
     *
     * @mbggenerated
     */
    public Date getTaskCreateTime() {
        return taskCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.task_create_time
     *
     * @param taskCreateTime the value for ec_sim_task.task_create_time
     *
     * @mbggenerated
     */
    public void setTaskCreateTime(Date taskCreateTime) {
        this.taskCreateTime = taskCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.task_state
     *
     * @return the value of ec_sim_task.task_state
     *
     * @mbggenerated
     */
    public String getTaskState() {
        return taskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.task_state
     *
     * @param taskState the value for ec_sim_task.task_state
     *
     * @mbggenerated
     */
    public void setTaskState(String taskState) {
        this.taskState = taskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.deal_user
     *
     * @return the value of ec_sim_task.deal_user
     *
     * @mbggenerated
     */
    public String getDealUser() {
        return dealUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.deal_user
     *
     * @param dealUser the value for ec_sim_task.deal_user
     *
     * @mbggenerated
     */
    public void setDealUser(String dealUser) {
        this.dealUser = dealUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.approve_user
     *
     * @return the value of ec_sim_task.approve_user
     *
     * @mbggenerated
     */
    public String getApproveUser() {
        return approveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.approve_user
     *
     * @param approveUser the value for ec_sim_task.approve_user
     *
     * @mbggenerated
     */
    public void setApproveUser(String approveUser) {
        this.approveUser = approveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.split_deal_user
     *
     * @return the value of ec_sim_task.split_deal_user
     *
     * @mbggenerated
     */
    public String getSplitDealUser() {
        return splitDealUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.split_deal_user
     *
     * @param splitDealUser the value for ec_sim_task.split_deal_user
     *
     * @mbggenerated
     */
    public void setSplitDealUser(String splitDealUser) {
        this.splitDealUser = splitDealUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.split_approve_user
     *
     * @return the value of ec_sim_task.split_approve_user
     *
     * @mbggenerated
     */
    public String getSplitApproveUser() {
        return splitApproveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.split_approve_user
     *
     * @param splitApproveUser the value for ec_sim_task.split_approve_user
     *
     * @mbggenerated
     */
    public void setSplitApproveUser(String splitApproveUser) {
        this.splitApproveUser = splitApproveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.create_date
     *
     * @return the value of ec_sim_task.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.create_date
     *
     * @param createDate the value for ec_sim_task.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.create_time
     *
     * @return the value of ec_sim_task.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.create_time
     *
     * @param createTime the value for ec_sim_task.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.create_user
     *
     * @return the value of ec_sim_task.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.create_user
     *
     * @param createUser the value for ec_sim_task.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.update_date
     *
     * @return the value of ec_sim_task.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.update_date
     *
     * @param updateDate the value for ec_sim_task.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.update_time
     *
     * @return the value of ec_sim_task.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.update_time
     *
     * @param updateTime the value for ec_sim_task.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.update_user
     *
     * @return the value of ec_sim_task.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.update_user
     *
     * @param updateUser the value for ec_sim_task.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.time_stamp
     *
     * @return the value of ec_sim_task.time_stamp
     *
     * @mbggenerated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.time_stamp
     *
     * @param timeStamp the value for ec_sim_task.time_stamp
     *
     * @mbggenerated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_sim_task.rec_stat
     *
     * @return the value of ec_sim_task.rec_stat
     *
     * @mbggenerated
     */
    public String getRecStat() {
        return recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_sim_task.rec_stat
     *
     * @param recStat the value for ec_sim_task.rec_stat
     *
     * @mbggenerated
     */
    public void setRecStat(String recStat) {
        this.recStat = recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_sim_task
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EcSimTask other = (EcSimTask) that;
        return (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
            && (this.getRuleId() == null ? other.getRuleId() == null : this.getRuleId().equals(other.getRuleId()))
            && (this.getSimilarPercent() == null ? other.getSimilarPercent() == null : this.getSimilarPercent().equals(other.getSimilarPercent()))
            && (this.getTaskCreateTime() == null ? other.getTaskCreateTime() == null : this.getTaskCreateTime().equals(other.getTaskCreateTime()))
            && (this.getTaskState() == null ? other.getTaskState() == null : this.getTaskState().equals(other.getTaskState()))
            && (this.getDealUser() == null ? other.getDealUser() == null : this.getDealUser().equals(other.getDealUser()))
            && (this.getApproveUser() == null ? other.getApproveUser() == null : this.getApproveUser().equals(other.getApproveUser()))
            && (this.getSplitDealUser() == null ? other.getSplitDealUser() == null : this.getSplitDealUser().equals(other.getSplitDealUser()))
            && (this.getSplitApproveUser() == null ? other.getSplitApproveUser() == null : this.getSplitApproveUser().equals(other.getSplitApproveUser()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getTimeStamp() == null ? other.getTimeStamp() == null : this.getTimeStamp().equals(other.getTimeStamp()))
            && (this.getRecStat() == null ? other.getRecStat() == null : this.getRecStat().equals(other.getRecStat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_sim_task
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
        result = prime * result + ((getRuleId() == null) ? 0 : getRuleId().hashCode());
        result = prime * result + ((getSimilarPercent() == null) ? 0 : getSimilarPercent().hashCode());
        result = prime * result + ((getTaskCreateTime() == null) ? 0 : getTaskCreateTime().hashCode());
        result = prime * result + ((getTaskState() == null) ? 0 : getTaskState().hashCode());
        result = prime * result + ((getDealUser() == null) ? 0 : getDealUser().hashCode());
        result = prime * result + ((getApproveUser() == null) ? 0 : getApproveUser().hashCode());
        result = prime * result + ((getSplitDealUser() == null) ? 0 : getSplitDealUser().hashCode());
        result = prime * result + ((getSplitApproveUser() == null) ? 0 : getSplitApproveUser().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getTimeStamp() == null) ? 0 : getTimeStamp().hashCode());
        result = prime * result + ((getRecStat() == null) ? 0 : getRecStat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_sim_task
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", taskId=").append(taskId);
        sb.append(", ruleId=").append(ruleId);
        sb.append(", similarPercent=").append(similarPercent);
        sb.append(", taskCreateTime=").append(taskCreateTime);
        sb.append(", taskState=").append(taskState);
        sb.append(", dealUser=").append(dealUser);
        sb.append(", approveUser=").append(approveUser);
        sb.append(", splitDealUser=").append(splitDealUser);
        sb.append(", splitApproveUser=").append(splitApproveUser);
        sb.append(", createDate=").append(createDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", recStat=").append(recStat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}