package cn.com.zsyk.crm.ecif.entity;

import java.io.Serializable;
import java.util.Date;

public class EcTagInclud implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_tag_includ.tag_id
     *
     * @mbggenerated
     */
    private String tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_tag_includ.includ_tag_id
     *
     * @mbggenerated
     */
    private String includTagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_tag_includ.tag_type_id
     *
     * @mbggenerated
     */
    private String tagTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_tag_includ.tag_name
     *
     * @mbggenerated
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_tag_includ.includ_tag_name
     *
     * @mbggenerated
     */
    private String includTagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_tag_includ.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_tag_includ.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_tag_includ.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_tag_includ.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_tag_includ.update_date
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_tag_includ.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_tag_includ.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_tag_includ.time_stamp
     *
     * @mbggenerated
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_tag_includ.rec_stat
     *
     * @mbggenerated
     */
    private String recStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ec_tag_includ
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_tag_includ.tag_id
     *
     * @return the value of ec_tag_includ.tag_id
     *
     * @mbggenerated
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_tag_includ.tag_id
     *
     * @param tagId the value for ec_tag_includ.tag_id
     *
     * @mbggenerated
     */
    public void setTagId(String tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_tag_includ.includ_tag_id
     *
     * @return the value of ec_tag_includ.includ_tag_id
     *
     * @mbggenerated
     */
    public String getIncludTagId() {
        return includTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_tag_includ.includ_tag_id
     *
     * @param includTagId the value for ec_tag_includ.includ_tag_id
     *
     * @mbggenerated
     */
    public void setIncludTagId(String includTagId) {
        this.includTagId = includTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_tag_includ.tag_type_id
     *
     * @return the value of ec_tag_includ.tag_type_id
     *
     * @mbggenerated
     */
    public String getTagTypeId() {
        return tagTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_tag_includ.tag_type_id
     *
     * @param tagTypeId the value for ec_tag_includ.tag_type_id
     *
     * @mbggenerated
     */
    public void setTagTypeId(String tagTypeId) {
        this.tagTypeId = tagTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_tag_includ.tag_name
     *
     * @return the value of ec_tag_includ.tag_name
     *
     * @mbggenerated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_tag_includ.tag_name
     *
     * @param tagName the value for ec_tag_includ.tag_name
     *
     * @mbggenerated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_tag_includ.includ_tag_name
     *
     * @return the value of ec_tag_includ.includ_tag_name
     *
     * @mbggenerated
     */
    public String getIncludTagName() {
        return includTagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_tag_includ.includ_tag_name
     *
     * @param includTagName the value for ec_tag_includ.includ_tag_name
     *
     * @mbggenerated
     */
    public void setIncludTagName(String includTagName) {
        this.includTagName = includTagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_tag_includ.remark
     *
     * @return the value of ec_tag_includ.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_tag_includ.remark
     *
     * @param remark the value for ec_tag_includ.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_tag_includ.create_date
     *
     * @return the value of ec_tag_includ.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_tag_includ.create_date
     *
     * @param createDate the value for ec_tag_includ.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_tag_includ.create_time
     *
     * @return the value of ec_tag_includ.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_tag_includ.create_time
     *
     * @param createTime the value for ec_tag_includ.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_tag_includ.create_user
     *
     * @return the value of ec_tag_includ.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_tag_includ.create_user
     *
     * @param createUser the value for ec_tag_includ.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_tag_includ.update_date
     *
     * @return the value of ec_tag_includ.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_tag_includ.update_date
     *
     * @param updateDate the value for ec_tag_includ.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_tag_includ.update_time
     *
     * @return the value of ec_tag_includ.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_tag_includ.update_time
     *
     * @param updateTime the value for ec_tag_includ.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_tag_includ.update_user
     *
     * @return the value of ec_tag_includ.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_tag_includ.update_user
     *
     * @param updateUser the value for ec_tag_includ.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_tag_includ.time_stamp
     *
     * @return the value of ec_tag_includ.time_stamp
     *
     * @mbggenerated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_tag_includ.time_stamp
     *
     * @param timeStamp the value for ec_tag_includ.time_stamp
     *
     * @mbggenerated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_tag_includ.rec_stat
     *
     * @return the value of ec_tag_includ.rec_stat
     *
     * @mbggenerated
     */
    public String getRecStat() {
        return recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_tag_includ.rec_stat
     *
     * @param recStat the value for ec_tag_includ.rec_stat
     *
     * @mbggenerated
     */
    public void setRecStat(String recStat) {
        this.recStat = recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_tag_includ
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EcTagInclud other = (EcTagInclud) that;
        return (this.getTagId() == null ? other.getTagId() == null : this.getTagId().equals(other.getTagId()))
            && (this.getIncludTagId() == null ? other.getIncludTagId() == null : this.getIncludTagId().equals(other.getIncludTagId()))
            && (this.getTagTypeId() == null ? other.getTagTypeId() == null : this.getTagTypeId().equals(other.getTagTypeId()))
            && (this.getTagName() == null ? other.getTagName() == null : this.getTagName().equals(other.getTagName()))
            && (this.getIncludTagName() == null ? other.getIncludTagName() == null : this.getIncludTagName().equals(other.getIncludTagName()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getTimeStamp() == null ? other.getTimeStamp() == null : this.getTimeStamp().equals(other.getTimeStamp()))
            && (this.getRecStat() == null ? other.getRecStat() == null : this.getRecStat().equals(other.getRecStat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_tag_includ
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTagId() == null) ? 0 : getTagId().hashCode());
        result = prime * result + ((getIncludTagId() == null) ? 0 : getIncludTagId().hashCode());
        result = prime * result + ((getTagTypeId() == null) ? 0 : getTagTypeId().hashCode());
        result = prime * result + ((getTagName() == null) ? 0 : getTagName().hashCode());
        result = prime * result + ((getIncludTagName() == null) ? 0 : getIncludTagName().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getTimeStamp() == null) ? 0 : getTimeStamp().hashCode());
        result = prime * result + ((getRecStat() == null) ? 0 : getRecStat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_tag_includ
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tagId=").append(tagId);
        sb.append(", includTagId=").append(includTagId);
        sb.append(", tagTypeId=").append(tagTypeId);
        sb.append(", tagName=").append(tagName);
        sb.append(", includTagName=").append(includTagName);
        sb.append(", remark=").append(remark);
        sb.append(", createDate=").append(createDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", recStat=").append(recStat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}