package cn.com.zsyk.crm.supply.mapper;

import cn.com.zsyk.crm.supply.entity.SysSmsSendGroup;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

public interface SysSmsSendGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SMS_SEND_GROUP
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SMS_SEND_GROUP
     *
     * @mbggenerated
     */
    int insert(SysSmsSendGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SMS_SEND_GROUP
     *
     * @mbggenerated
     */
    SysSmsSendGroup selectByPrimaryKey(BigDecimal msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SMS_SEND_GROUP
     *
     * @mbggenerated
     */
    List<SysSmsSendGroup> selectAll(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SMS_SEND_GROUP
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysSmsSendGroup record);

    List<Map<String,String>> selectPhoneByGroupId(@Param("groupId") String groupId);
}