spring: 
  profiles: eureka1

server:
  port: 7001

eureka:
  server: 
    enable-self-preservation: true
  instance:
    hostname: eureka1
  client: 
    #register-with-eureka: false
    #fetch-registry: false
    service-url: 
      default-zone: http://eureka2:7002/eureka
