server:
  port: 8088
  context-path: / #设定应用的context-path
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  application:
      name: ${appName:crm-zuul}
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//122.51.104.204:1521/orcl
    username: crmdev
    password: 123456
  redis:
    host: 122.51.104.204
    password:
    port: 6379
  rabbitmq:
    host: 122.51.104.204
    port: 5672
    username: admin
    password: admin
  jackson:
    time-zone: GMT+8
  sleuth:
    http:
      enabled: true
    sampler:
      probability: 1.0
    zuul:
      enabled: true
#mybatis:
  mapper-locations: classpath:mapper/*.xml
zuul:
  retryable: true
  sensitiveHeaders:
  ignoredServices: '*'
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000
eureka:
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:8010/eureka
auth:
  loginPath: /ui/comm/login
  excludePaths: [
    /crm-manage/crm/manage/getKaptchaImage,
    /crm-manage/crm/manage/usermng/userLoginChk
  ]