###################  生产环境配置     ###################
debug: false
spring:
  profiles: pro
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: root

server:
  port: 8082  
  context-path: / #设定应用的context-path.
  compression: 
    enabled: true  #是否开启压缩，默认为false.
#  ssl: 
#    key-store: classpath:keystore.p12
#    key-store-password: 111111
#    keyStoreType: PKCS12