###################  测试环境配置     ###################
debug: true

spring:
  profiles: test
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//122.51.104.204:1521/orcl
    username: crmdev
    password: 123456

server:
  port: 8081
