###################  开发环境配置     ###################
info:
  log-switch: 
    service: true #Service日志开关，在common模块已制定
    
server:
  port: 8080
  context-path: / #设定应用的context-path
    
spring:
  profiles: dev 
  application: 
    name: ${appName:crm-ecif}
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 20Mb
      max-request-size: 20Mb    
mybatis: 
  mapper-packages:  cn.com.zsyk.crm.ecif.mapper        #Mapper接口扫描目录
  mapper-locations: classpath:mapper/ecif/*.xml       #xml文件扫描目录
  type-aliases-package: cn.com.zsyk.crm.ecif.entity    #别名扫描目录 

logging:
  level:
     cn.com.zsyk.crm.ecif.mapper : debug
 