package cn.com.zsyk.crm.ocrm.mapper;

import cn.com.zsyk.crm.ocrm.entity.OcBusiOpp;
import java.util.List;

public interface OcBusiOppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_busi_opp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String busiOppNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_busi_opp
     *
     * @mbggenerated
     */
    int insert(OcBusiOpp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_busi_opp
     *
     * @mbggenerated
     */
    OcBusiOpp selectByPrimaryKey(String busiOppNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_busi_opp
     *
     * @mbggenerated
     */
    List<OcBusiOpp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_busi_opp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OcBusiOpp record);

    /**
     * Desc: 动态查询
     * @param ocBusiOpp
     * @return
     * @author
     */
	List<OcBusiOpp> selectBusiOppList(OcBusiOpp ocBusiOpp);
	
	List<OcBusiOpp> selectGrpFollowUpByCustAgen();
}