package cn.com.zsyk.crm.ocrm.mapper;

import cn.com.zsyk.crm.ocrm.entity.OcGrpCustTrace;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OcGrpCustTraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_grp_cust_trace
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("traceId") String traceId, @Param("custNo") String custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_grp_cust_trace
     *
     * @mbggenerated
     */
    int insert(OcGrpCustTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_grp_cust_trace
     *
     * @mbggenerated
     */
    OcGrpCustTrace selectByPrimaryKey(@Param("traceId") String traceId, @Param("custNo") String custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_grp_cust_trace
     *
     * @mbggenerated
     */
    List<OcGrpCustTrace> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_grp_cust_trace
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OcGrpCustTrace record);
    
    List<OcGrpCustTrace> selectByEntity(OcGrpCustTrace record);
}