package cn.com.zsyk.crm.ocrm.mapper;

import cn.com.zsyk.crm.ocrm.entity.OcGrpTrace;
import java.util.List;

public interface OcGrpTraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_grp_trace
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String traceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_grp_trace
     *
     * @mbggenerated
     */
    int insert(OcGrpTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_grp_trace
     *
     * @mbggenerated
     */
    OcGrpTrace selectByPrimaryKey(String traceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_grp_trace
     *
     * @mbggenerated
     */
    List<OcGrpTrace> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_grp_trace
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OcGrpTrace record);
    
    List<OcGrpTrace> selectByEntity(OcGrpTrace record);
    
    List<OcGrpTrace> selectMaxCustNumByGroupId(String groupId);
}