package cn.com.zsyk.crm.ecif.mapper;

import cn.com.zsyk.crm.ecif.entity.EcContactWay;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcContactWayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_contact_way
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("custNo") String custNo, @Param("contactSqn") Integer contactSqn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_contact_way
     *
     * @mbggenerated
     */
    int insert(EcContactWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_contact_way
     *
     * @mbggenerated
     */
    EcContactWay selectByPrimaryKey(@Param("custNo") String custNo, @Param("contactSqn") Integer contactSqn);
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table ec_contact_way
	 *
	 * @mbggenerated
	 */
	List<EcContactWay> selectByPrimaryKeyList(@Param("custNo") String custNo);

	List<EcContactWay> getContactWayOneList(@Param("custNo") String custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_contact_way
     *
     * @mbggenerated
     */
    List<EcContactWay> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_contact_way
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EcContactWay record);
    //设置联系方式列表为失效  add lijiangcheng 2019-08-27
    int updateByCustNoPhone(@Param("custNo") String custNo, @Param("recStat") String recStat);
            /**
     * Desc: 根据客户号获取联系信息
     * @param ecContactWay
     * @return
     * @author
     */
	List<EcContactWay> selectContactWayList(EcContactWay ecContactWay);

	/**
	 * Desc: 根据客户逻辑删除信息
	 * @param custNo
	 * @return
	 * @author
	 */
	int deleteByCustNo(String custNo);
	/**
	 * Desc: 获取下一个Sqn
	 * @param custNo
	 * @return
	 * @author
	 */
	int getNextSqnByCustNo(String custNo);

	EcContactWay selectByCustNoMinSqn(String custNo);

	String selectCustNo(String custNo);

}