package cn.com.zsyk.crm.ecif.mapper;

import cn.com.zsyk.crm.ecif.entity.EcCustAgent;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcCustAgentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_agent
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("custNo") String custNo, @Param("origSysAgentNo") String origSysAgentNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_agent
     *
     * @mbggenerated
     */
    int insert(EcCustAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_agent
     *
     * @mbggenerated
     */
    EcCustAgent selectByPrimaryKey(@Param("custNo") String custNo, @Param("origSysAgentNo") String origSysAgentNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_agent
     *
     * @mbggenerated
     */
    List<EcCustAgent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_agent
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EcCustAgent record);

    /**
     * Desc: 查询客户代理人列表
     * @param ecCustAgent
     * @return
     * @author
     */
	List<EcCustAgent> selectCustAgentList(EcCustAgent ecCustAgent);

	/**
	 * Desc: 根据客户逻辑删除信息
	 * @param custNo
	 * @return
	 * @author
	 */
	int deleteByCustNo(String custNo);
}