package cn.com.zsyk.crm.ecif.mapper;

import cn.com.zsyk.crm.ecif.entity.EcCustSplitRela;
import java.util.List;

public interface EcCustSplitRelaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_split_rela
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String splitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_split_rela
     *
     * @mbggenerated
     */
    int insert(EcCustSplitRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_split_rela
     *
     * @mbggenerated
     */
    EcCustSplitRela selectByPrimaryKey(String splitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_split_rela
     *
     * @mbggenerated
     */
    List<EcCustSplitRela> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_split_rela
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EcCustSplitRela record);
}