package cn.com.zsyk.crm.ecif.mapper;

import cn.com.zsyk.crm.ecif.entity.EcCustTouch;
import java.util.List;

public interface EcCustTouchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_contact
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String contactNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_contact
     *
     * @mbggenerated
     */
    int insert(EcCustTouch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_contact
     *
     * @mbggenerated
     */
    EcCustTouch selectByPrimaryKey(String contactNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_contact
     *
     * @mbggenerated
     */
    List<EcCustTouch> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_contact
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EcCustTouch record);

    /**
     * Desc: 查询客户接触信息列表
     * @param EcCustTouch
     * @return
     * @author
     */
	List<EcCustTouch> selectcustTouchList(EcCustTouch ecCustTouch);

	/**
	 * Desc: 根据客户逻辑删除信息
	 * @param custNo
	 * @return
	 * @author
	 */
	int deleteByCustNo(String custNo);
}