package cn.com.zsyk.crm.ecif.mapper;

import cn.com.zsyk.crm.ecif.entity.EcCustSaleChgTrace;
import java.util.List;

public interface EcCustSaleChgTraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_sale_chg_trace
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long traceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_sale_chg_trace
     *
     * @mbggenerated
     */
    int insert(EcCustSaleChgTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_sale_chg_trace
     *
     * @mbggenerated
     */
    EcCustSaleChgTrace selectByPrimaryKey(Long traceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_sale_chg_trace
     *
     * @mbggenerated
     */
    List<EcCustSaleChgTrace> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_sale_chg_trace
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EcCustSaleChgTrace record);
}