package cn.com.zsyk.crm.ecif.mapper;

import cn.com.zsyk.crm.ecif.entity.EcCustDemand;
import java.util.List;

public interface EcCustDemandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_demand
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String demandNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_demand
     *
     * @mbggenerated
     */
    int insert(EcCustDemand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_demand
     *
     * @mbggenerated
     */
    EcCustDemand selectByPrimaryKey(String demandNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_demand
     *
     * @mbggenerated
     */
    List<EcCustDemand> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_demand
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EcCustDemand record);

    /**
     * Desc: 查询客户需求列表
     * @param custNo
     * @return
     * @author
     */
	List<EcCustDemand> selectByCustNo(String custNo);

	/**
	 * Desc: 根据客户逻辑删除信息
	 * @param custNo
	 * @return
	 * @author
	 */
	int deleteByCustNo(String custNo);
}