package cn.com.zsyk.crm.ecif.mapper;

import cn.com.zsyk.crm.ecif.entity.EcCustProduct;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcCustProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("custNo") String custNo, @Param("productCd") String productCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_product
     *
     * @mbggenerated
     */
    int insert(EcCustProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_product
     *
     * @mbggenerated
     */
    EcCustProduct selectByPrimaryKey(@Param("custNo") String custNo, @Param("productCd") String productCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_product
     *
     * @mbggenerated
     */
    List<EcCustProduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_cust_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EcCustProduct record);

    /**
     * Desc: 查询客户产品列表
     * @param custNo
     * @return
     * @author
     */
	List<EcCustProduct> selectByCustNo(String custNo);

	/**
	 * Desc: 根据客户逻辑删除信息
	 * @param custNo
	 * @author
	 */
	int deleteByCustNo(String custNo);
}