package cn.com.zsyk.crm.ecif.mapper;

import cn.com.zsyk.crm.ecif.entity.EcTagInclud;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcTagIncludMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_tag_includ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("tagId") String tagId, @Param("includTagId") String includTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_tag_includ
     *
     * @mbggenerated
     */
    int insert(EcTagInclud record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_tag_includ
     *
     * @mbggenerated
     */
    EcTagInclud selectByPrimaryKey(@Param("tagId") String tagId, @Param("includTagId") String includTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_tag_includ
     *
     * @mbggenerated
     */
    List<EcTagInclud> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_tag_includ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EcTagInclud record);
    
    List<EcTagInclud> selectByEntity(EcTagInclud record);
}