package cn.com.zsyk.crm.ecif.mapper;

import cn.com.zsyk.crm.ecif.entity.EcTagMutex;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcTagMutexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_tag_mutex
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("ruleSeqNo") String ruleSeqNo, @Param("tagId") String tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_tag_mutex
     *
     * @mbggenerated
     */
    int insert(EcTagMutex record);

    int insertRest(EcTagMutex record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_tag_mutex
     *
     * @mbggenerated
     */
    EcTagMutex selectByPrimaryKey(@Param("ruleSeqNo") String ruleSeqNo, @Param("tagId") String tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_tag_mutex
     *
     * @mbggenerated
     */
    List<EcTagMutex> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_tag_mutex
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EcTagMutex record);
    
    /**
     * 逻辑删除
     * @param record
     * @return
     */
    int update(EcTagMutex record);
    
    
    /**
     * 查询互斥列表（任意输入互斥序号、标签名称、标签id）
     * @param record
     * @return
     */
    List<EcTagMutex> selectByEntity(EcTagMutex record);
}