package cn.com.zsyk.crm.ecif.mapper;

import cn.com.zsyk.crm.ecif.entity.EcTrackInfo;
import java.util.List;

public interface EcTrackInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_track_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String trackCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_track_info
     *
     * @mbggenerated
     */
    int insert(EcTrackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_track_info
     *
     * @mbggenerated
     */
    EcTrackInfo selectByPrimaryKey(String trackCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_track_info
     *
     * @mbggenerated
     */
    List<EcTrackInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_track_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EcTrackInfo record);

    /**
     * Desc: 根据客户号查询客户动态轨迹列表
     * @param custNo
     * @author
     */
    List<EcTrackInfo> selectByCustNo(String custNo);

    /**
     * Desc: 根据客户逻辑删除信息
     * @param custNo
     * @return
     * @author
     */
	int deleteByCustNo(String custNo);
    /**
     * Desc: 查询客户动态轨迹列表
     * @param custNo
     * @author
     */
	List<EcTrackInfo> selectCustDyncTrackList(EcTrackInfo ecTrackInfo);
}