package cn.com.zsyk.crm.manage.mapper;

import cn.com.zsyk.crm.manage.entity.SysCounty;

import java.util.List;

public interface SysCountyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_county
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String countyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_county
     *
     * @mbggenerated
     */
    int insert(SysCounty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_county
     *
     * @mbggenerated
     */
    SysCounty selectByPrimaryKey(String countyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_county
     *
     * @mbggenerated
     */
    List<SysCounty> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_county
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysCounty record);

    /**
     * Desc: 根据市查询区县列表
     * @param provinceCode
     * @param cityCode
     * @return
     * @author
     */
	List<SysCounty> selectByProvCityCd(String provinceCode, String cityCode);


    String selectCode(SysCounty record);
}