package cn.com.zsyk.crm.manage.mapper;

import cn.com.zsyk.crm.manage.entity.SysCity;
import java.util.List;

public interface SysCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_city
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cityCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_city
     *
     * @mbggenerated
     */
    int insert(SysCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_city
     *
     * @mbggenerated
     */
    SysCity selectByPrimaryKey(String cityCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_city
     *
     * @mbggenerated
     */
    List<SysCity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysCity record);

    /**
     * Desc: 根据省查询市列表
     * @param provinceCode
     * @return
     * @author
     */
	List<SysCity> selectByProvCd(String provinceCode);

    String selectCode(String cityName);
}