package cn.com.zsyk.crm.manage.mapper;

import cn.com.zsyk.crm.manage.entity.SysLoginLog;
import java.util.List;

public interface SysLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOGIN_LOG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOGIN_LOG
     *
     * @mbggenerated
     */
    int insert(SysLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOGIN_LOG
     *
     * @mbggenerated
     */
    SysLoginLog selectByPrimaryKey(String seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOGIN_LOG
     *
     * @mbggenerated
     */
    List<SysLoginLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOGIN_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysLoginLog record);
}