package cn.com.zsyk.crm.manage.mapper;

import cn.com.zsyk.crm.manage.entity.SysRuleFactorParam;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRuleFactorParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_factor_param
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("paramName") String paramName, @Param("itemCode") String itemCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_factor_param
     *
     * @mbggenerated
     */
    int insert(SysRuleFactorParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_factor_param
     *
     * @mbggenerated
     */
    SysRuleFactorParam selectByPrimaryKey(@Param("paramName") String paramName, @Param("itemCode") String itemCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_factor_param
     *
     * @mbggenerated
     */
    List<SysRuleFactorParam> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_factor_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRuleFactorParam record);

    List<SysRuleFactorParam> selectAllRec();
    
    List<SysRuleFactorParam> selectByEntity(SysRuleFactorParam record);
    
    List<SysRuleFactorParam> getByEntity(SysRuleFactorParam record);
    
}