package cn.com.zsyk.crm.manage.mapper;

import cn.com.zsyk.crm.manage.entity.SysRuleCombineBaseRel;
import java.util.List;

public interface SysRuleCombineBaseRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_combine_base_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_combine_base_rel
     *
     * @mbggenerated
     */
    int insert(SysRuleCombineBaseRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_combine_base_rel
     *
     * @mbggenerated
     */
    SysRuleCombineBaseRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_combine_base_rel
     *
     * @mbggenerated
     */
    List<SysRuleCombineBaseRel> selectAll();
    
    List<SysRuleCombineBaseRel> selectAllByCombineRuleId(String combineRuleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_combine_base_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRuleCombineBaseRel record);
}