package cn.com.zsyk.crm.manage.mapper;

import cn.com.zsyk.crm.manage.entity.SysRuleBaseRule;
import cn.com.zsyk.crm.manage.entity.SysRuleCombineRule;
import java.util.List;
import java.util.Map;

public interface SysRuleCombineRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_combine_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String combineRuleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_combine_rule
     *
     * @mbggenerated
     */
    int insert(SysRuleCombineRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_combine_rule
     *
     * @mbggenerated
     */
    SysRuleCombineRule selectByPrimaryKey(String combineRuleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_combine_rule
     *
     * @mbggenerated
     */
    List<SysRuleCombineRule> selectAll();

    List<SysRuleCombineRule> selectAllByEntity(SysRuleCombineRule record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_combine_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRuleCombineRule record);
    
    
    


    int saveCombineRule(SysRuleCombineRule combineRule);

    int saveCombineBaseRel(Map factorMap);

    List<SysRuleCombineRule> findAll(SysRuleCombineRule combineRule);

    List<Map> findCombineBaseRels(String combineRuleId);

    List<Map> findCombineBaseRelsDetail(String combineRuleId);

    SysRuleCombineRule findById(String combineRuleId);

    void updateCombineRule(SysRuleCombineRule cbr);

    List<SysRuleCombineRule> findCombineRulesByBaseRuleId(String id);

    int findByName(SysRuleCombineRule cbr);
}