package cn.com.zsyk.crm.manage.mapper;

import cn.com.zsyk.crm.manage.bom.SysTagInfo;
import cn.com.zsyk.crm.manage.entity.SysTag;

import java.util.List;

public interface SysTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    int insert(SysTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    SysTag selectByPrimaryKey(Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    List<SysTag> selectAll();
    List<SysTag> selectByTagNamType(SysTag record);
    List<SysTagInfo> selectByEntity(SysTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysTag record);
    
    
    List<String> selectByStrategyId (String strategyId);
}