logging:
  config: classpath:log4j2.xml
    
spring:
  profiles: dev
  application:
    name: crm-scheduler

server:
  port: 8000

scheduler:
  target:
    ecif:
      ip: 10.16.8.142
      port: 8080
    manage:
      ip: 10.16.8.142
      port: 8082
    ocrm:
      ip: 10.16.8.142
      port: 8083
    query:
      ip: 10.16.8.142
      port: 8085