###################  开发环境配置     ###################
#info一般配置用户自定义信息，在actuatr的/info端点可显示（使用@***@从pom.xml中获取信息）
info:
  log-switch: 
    service: true
server:
  port: 8085
  context-path: / #设定应用的context-path
    
spring:
  profiles: dev  
  application: 
    name: crm-query
  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@//10.16.8.23:1521/fxqtest
#    username: zkrprpall
#    password: sinosoft
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//122.51.104.204:1521/orcl
    username: crmdev
    password: 123456

#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@//10.16.8.117:1521/rsoracle
#    username: odm
#    password: odm

mybatis:
  mapper-packages:  cn.com.zsyk.crm.query.mapper        #Mapper接口扫描目录
  mapper-locations: classpath:mapper/query/*.xml       #xml文件扫描目录
  type-aliases-package: cn.com.zsyk.crm.query.entity    #别名扫描目录

logging:
  level:
     cn.com.zsyk.crm.query.mapper : debug

