package cn.com.zsyk.crm.ocrm.entity;

import java.io.Serializable;
import java.util.Date;

public class OcGrpTrace implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_grp_trace.trace_id
     *
     * @mbggenerated
     */
    private String traceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_grp_trace.group_id
     *
     * @mbggenerated
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_grp_trace.cust_num
     *
     * @mbggenerated
     */
    private Integer custNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_grp_trace.establish_date
     *
     * @mbggenerated
     */
    private Date establishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_grp_trace.strategy_id
     *
     * @mbggenerated
     */
    private String strategyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_grp_trace.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_grp_trace.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_grp_trace.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_grp_trace.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_grp_trace.update_date
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_grp_trace.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_grp_trace.time_stamp
     *
     * @mbggenerated
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_grp_trace.rec_stat
     *
     * @mbggenerated
     */
    private String recStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oc_grp_trace
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_grp_trace.trace_id
     *
     * @return the value of oc_grp_trace.trace_id
     *
     * @mbggenerated
     */
    public String getTraceId() {
        return traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_grp_trace.trace_id
     *
     * @param traceId the value for oc_grp_trace.trace_id
     *
     * @mbggenerated
     */
    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_grp_trace.group_id
     *
     * @return the value of oc_grp_trace.group_id
     *
     * @mbggenerated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_grp_trace.group_id
     *
     * @param groupId the value for oc_grp_trace.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_grp_trace.cust_num
     *
     * @return the value of oc_grp_trace.cust_num
     *
     * @mbggenerated
     */
    public Integer getCustNum() {
        return custNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_grp_trace.cust_num
     *
     * @param custNum the value for oc_grp_trace.cust_num
     *
     * @mbggenerated
     */
    public void setCustNum(Integer custNum) {
        this.custNum = custNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_grp_trace.establish_date
     *
     * @return the value of oc_grp_trace.establish_date
     *
     * @mbggenerated
     */
    public Date getEstablishDate() {
        return establishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_grp_trace.establish_date
     *
     * @param establishDate the value for oc_grp_trace.establish_date
     *
     * @mbggenerated
     */
    public void setEstablishDate(Date establishDate) {
        this.establishDate = establishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_grp_trace.strategy_id
     *
     * @return the value of oc_grp_trace.strategy_id
     *
     * @mbggenerated
     */
    public String getStrategyId() {
        return strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_grp_trace.strategy_id
     *
     * @param strategyId the value for oc_grp_trace.strategy_id
     *
     * @mbggenerated
     */
    public void setStrategyId(String strategyId) {
        this.strategyId = strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_grp_trace.create_user
     *
     * @return the value of oc_grp_trace.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_grp_trace.create_user
     *
     * @param createUser the value for oc_grp_trace.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_grp_trace.create_date
     *
     * @return the value of oc_grp_trace.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_grp_trace.create_date
     *
     * @param createDate the value for oc_grp_trace.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_grp_trace.create_time
     *
     * @return the value of oc_grp_trace.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_grp_trace.create_time
     *
     * @param createTime the value for oc_grp_trace.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_grp_trace.update_user
     *
     * @return the value of oc_grp_trace.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_grp_trace.update_user
     *
     * @param updateUser the value for oc_grp_trace.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_grp_trace.update_date
     *
     * @return the value of oc_grp_trace.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_grp_trace.update_date
     *
     * @param updateDate the value for oc_grp_trace.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_grp_trace.update_time
     *
     * @return the value of oc_grp_trace.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_grp_trace.update_time
     *
     * @param updateTime the value for oc_grp_trace.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_grp_trace.time_stamp
     *
     * @return the value of oc_grp_trace.time_stamp
     *
     * @mbggenerated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_grp_trace.time_stamp
     *
     * @param timeStamp the value for oc_grp_trace.time_stamp
     *
     * @mbggenerated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_grp_trace.rec_stat
     *
     * @return the value of oc_grp_trace.rec_stat
     *
     * @mbggenerated
     */
    public String getRecStat() {
        return recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_grp_trace.rec_stat
     *
     * @param recStat the value for oc_grp_trace.rec_stat
     *
     * @mbggenerated
     */
    public void setRecStat(String recStat) {
        this.recStat = recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_grp_trace
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OcGrpTrace other = (OcGrpTrace) that;
        return (this.getTraceId() == null ? other.getTraceId() == null : this.getTraceId().equals(other.getTraceId()))
            && (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
            && (this.getCustNum() == null ? other.getCustNum() == null : this.getCustNum().equals(other.getCustNum()))
            && (this.getEstablishDate() == null ? other.getEstablishDate() == null : this.getEstablishDate().equals(other.getEstablishDate()))
            && (this.getStrategyId() == null ? other.getStrategyId() == null : this.getStrategyId().equals(other.getStrategyId()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getTimeStamp() == null ? other.getTimeStamp() == null : this.getTimeStamp().equals(other.getTimeStamp()))
            && (this.getRecStat() == null ? other.getRecStat() == null : this.getRecStat().equals(other.getRecStat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_grp_trace
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTraceId() == null) ? 0 : getTraceId().hashCode());
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getCustNum() == null) ? 0 : getCustNum().hashCode());
        result = prime * result + ((getEstablishDate() == null) ? 0 : getEstablishDate().hashCode());
        result = prime * result + ((getStrategyId() == null) ? 0 : getStrategyId().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getTimeStamp() == null) ? 0 : getTimeStamp().hashCode());
        result = prime * result + ((getRecStat() == null) ? 0 : getRecStat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oc_grp_trace
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", traceId=").append(traceId);
        sb.append(", groupId=").append(groupId);
        sb.append(", custNum=").append(custNum);
        sb.append(", establishDate=").append(establishDate);
        sb.append(", strategyId=").append(strategyId);
        sb.append(", createUser=").append(createUser);
        sb.append(", createDate=").append(createDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", recStat=").append(recStat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}