package cn.com.zsyk.crm.manage.entity;

import java.io.Serializable;
import java.util.Date;

public class SysMonitorTaskDealDef implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_monitor_task_deal_def.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_monitor_task_deal_def.monitor_id
     *
     * @mbggenerated
     */
    private String monitorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_monitor_task_deal_def.risk_level
     *
     * @mbggenerated
     */
    private String riskLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_monitor_task_deal_def.deal_level
     *
     * @mbggenerated
     */
    private String dealLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_monitor_task_deal_def.is_risk
     *
     * @mbggenerated
     */
    private String isRisk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_monitor_task_deal_def.deal_result
     *
     * @mbggenerated
     */
    private String dealResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_monitor_task_deal_def.deal_idea
     *
     * @mbggenerated
     */
    private String dealIdea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_monitor_task_deal_def.operater
     *
     * @mbggenerated
     */
    private String operater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_monitor_task_deal_def.operate_date
     *
     * @mbggenerated
     */
    private Date operateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_monitor_task_deal_def
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_monitor_task_deal_def.id
     *
     * @return the value of sys_monitor_task_deal_def.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_monitor_task_deal_def.id
     *
     * @param id the value for sys_monitor_task_deal_def.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_monitor_task_deal_def.monitor_id
     *
     * @return the value of sys_monitor_task_deal_def.monitor_id
     *
     * @mbggenerated
     */
    public String getMonitorId() {
        return monitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_monitor_task_deal_def.monitor_id
     *
     * @param monitorId the value for sys_monitor_task_deal_def.monitor_id
     *
     * @mbggenerated
     */
    public void setMonitorId(String monitorId) {
        this.monitorId = monitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_monitor_task_deal_def.risk_level
     *
     * @return the value of sys_monitor_task_deal_def.risk_level
     *
     * @mbggenerated
     */
    public String getRiskLevel() {
        return riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_monitor_task_deal_def.risk_level
     *
     * @param riskLevel the value for sys_monitor_task_deal_def.risk_level
     *
     * @mbggenerated
     */
    public void setRiskLevel(String riskLevel) {
        this.riskLevel = riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_monitor_task_deal_def.deal_level
     *
     * @return the value of sys_monitor_task_deal_def.deal_level
     *
     * @mbggenerated
     */
    public String getDealLevel() {
        return dealLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_monitor_task_deal_def.deal_level
     *
     * @param dealLevel the value for sys_monitor_task_deal_def.deal_level
     *
     * @mbggenerated
     */
    public void setDealLevel(String dealLevel) {
        this.dealLevel = dealLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_monitor_task_deal_def.is_risk
     *
     * @return the value of sys_monitor_task_deal_def.is_risk
     *
     * @mbggenerated
     */
    public String getIsRisk() {
        return isRisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_monitor_task_deal_def.is_risk
     *
     * @param isRisk the value for sys_monitor_task_deal_def.is_risk
     *
     * @mbggenerated
     */
    public void setIsRisk(String isRisk) {
        this.isRisk = isRisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_monitor_task_deal_def.deal_result
     *
     * @return the value of sys_monitor_task_deal_def.deal_result
     *
     * @mbggenerated
     */
    public String getDealResult() {
        return dealResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_monitor_task_deal_def.deal_result
     *
     * @param dealResult the value for sys_monitor_task_deal_def.deal_result
     *
     * @mbggenerated
     */
    public void setDealResult(String dealResult) {
        this.dealResult = dealResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_monitor_task_deal_def.deal_idea
     *
     * @return the value of sys_monitor_task_deal_def.deal_idea
     *
     * @mbggenerated
     */
    public String getDealIdea() {
        return dealIdea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_monitor_task_deal_def.deal_idea
     *
     * @param dealIdea the value for sys_monitor_task_deal_def.deal_idea
     *
     * @mbggenerated
     */
    public void setDealIdea(String dealIdea) {
        this.dealIdea = dealIdea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_monitor_task_deal_def.operater
     *
     * @return the value of sys_monitor_task_deal_def.operater
     *
     * @mbggenerated
     */
    public String getOperater() {
        return operater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_monitor_task_deal_def.operater
     *
     * @param operater the value for sys_monitor_task_deal_def.operater
     *
     * @mbggenerated
     */
    public void setOperater(String operater) {
        this.operater = operater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_monitor_task_deal_def.operate_date
     *
     * @return the value of sys_monitor_task_deal_def.operate_date
     *
     * @mbggenerated
     */
    public Date getOperateDate() {
        return operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_monitor_task_deal_def.operate_date
     *
     * @param operateDate the value for sys_monitor_task_deal_def.operate_date
     *
     * @mbggenerated
     */
    public void setOperateDate(Date operateDate) {
        this.operateDate = operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_monitor_task_deal_def
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysMonitorTaskDealDef other = (SysMonitorTaskDealDef) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMonitorId() == null ? other.getMonitorId() == null : this.getMonitorId().equals(other.getMonitorId()))
            && (this.getRiskLevel() == null ? other.getRiskLevel() == null : this.getRiskLevel().equals(other.getRiskLevel()))
            && (this.getDealLevel() == null ? other.getDealLevel() == null : this.getDealLevel().equals(other.getDealLevel()))
            && (this.getIsRisk() == null ? other.getIsRisk() == null : this.getIsRisk().equals(other.getIsRisk()))
            && (this.getDealResult() == null ? other.getDealResult() == null : this.getDealResult().equals(other.getDealResult()))
            && (this.getDealIdea() == null ? other.getDealIdea() == null : this.getDealIdea().equals(other.getDealIdea()))
            && (this.getOperater() == null ? other.getOperater() == null : this.getOperater().equals(other.getOperater()))
            && (this.getOperateDate() == null ? other.getOperateDate() == null : this.getOperateDate().equals(other.getOperateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_monitor_task_deal_def
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMonitorId() == null) ? 0 : getMonitorId().hashCode());
        result = prime * result + ((getRiskLevel() == null) ? 0 : getRiskLevel().hashCode());
        result = prime * result + ((getDealLevel() == null) ? 0 : getDealLevel().hashCode());
        result = prime * result + ((getIsRisk() == null) ? 0 : getIsRisk().hashCode());
        result = prime * result + ((getDealResult() == null) ? 0 : getDealResult().hashCode());
        result = prime * result + ((getDealIdea() == null) ? 0 : getDealIdea().hashCode());
        result = prime * result + ((getOperater() == null) ? 0 : getOperater().hashCode());
        result = prime * result + ((getOperateDate() == null) ? 0 : getOperateDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_monitor_task_deal_def
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", monitorId=").append(monitorId);
        sb.append(", riskLevel=").append(riskLevel);
        sb.append(", dealLevel=").append(dealLevel);
        sb.append(", isRisk=").append(isRisk);
        sb.append(", dealResult=").append(dealResult);
        sb.append(", dealIdea=").append(dealIdea);
        sb.append(", operater=").append(operater);
        sb.append(", operateDate=").append(operateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}