package cn.com.zsyk.crm.manage.entity;

import java.io.Serializable;
import java.util.Date;

public class SysMenuInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.menu_code
     *
     * @mbggenerated
     */
    private String menuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.menu_name
     *
     * @mbggenerated
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.menu_lv
     *
     * @mbggenerated
     */
    private String menuLv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.node_path
     *
     * @mbggenerated
     */
    private String nodePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.pare_menu_code
     *
     * @mbggenerated
     */
    private String pareMenuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.pare_menu
     *
     * @mbggenerated
     */
    private String pareMenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.menu_order
     *
     * @mbggenerated
     */
    private String menuOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.menu_desc
     *
     * @mbggenerated
     */
    private String menuDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.update_date
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.time_stamp
     *
     * @mbggenerated
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcs_menu_info.rec_stat
     *
     * @mbggenerated
     */
    private String recStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zcs_menu_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.menu_code
     *
     * @return the value of zcs_menu_info.menu_code
     *
     * @mbggenerated
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.menu_code
     *
     * @param menuCode the value for zcs_menu_info.menu_code
     *
     * @mbggenerated
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.menu_name
     *
     * @return the value of zcs_menu_info.menu_name
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.menu_name
     *
     * @param menuName the value for zcs_menu_info.menu_name
     *
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.menu_lv
     *
     * @return the value of zcs_menu_info.menu_lv
     *
     * @mbggenerated
     */
    public String getMenuLv() {
        return menuLv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.menu_lv
     *
     * @param menuLv the value for zcs_menu_info.menu_lv
     *
     * @mbggenerated
     */
    public void setMenuLv(String menuLv) {
        this.menuLv = menuLv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.node_path
     *
     * @return the value of zcs_menu_info.node_path
     *
     * @mbggenerated
     */
    public String getNodePath() {
        return nodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.node_path
     *
     * @param nodePath the value for zcs_menu_info.node_path
     *
     * @mbggenerated
     */
    public void setNodePath(String nodePath) {
        this.nodePath = nodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.pare_menu_code
     *
     * @return the value of zcs_menu_info.pare_menu_code
     *
     * @mbggenerated
     */
    public String getPareMenuCode() {
        return pareMenuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.pare_menu_code
     *
     * @param pareMenuCode the value for zcs_menu_info.pare_menu_code
     *
     * @mbggenerated
     */
    public void setPareMenuCode(String pareMenuCode) {
        this.pareMenuCode = pareMenuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.pare_menu
     *
     * @return the value of zcs_menu_info.pare_menu
     *
     * @mbggenerated
     */
    public String getPareMenu() {
        return pareMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.pare_menu
     *
     * @param pareMenu the value for zcs_menu_info.pare_menu
     *
     * @mbggenerated
     */
    public void setPareMenu(String pareMenu) {
        this.pareMenu = pareMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.menu_order
     *
     * @return the value of zcs_menu_info.menu_order
     *
     * @mbggenerated
     */
    public String getMenuOrder() {
        return menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.menu_order
     *
     * @param menuOrder the value for zcs_menu_info.menu_order
     *
     * @mbggenerated
     */
    public void setMenuOrder(String menuOrder) {
        this.menuOrder = menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.menu_desc
     *
     * @return the value of zcs_menu_info.menu_desc
     *
     * @mbggenerated
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.menu_desc
     *
     * @param menuDesc the value for zcs_menu_info.menu_desc
     *
     * @mbggenerated
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.create_date
     *
     * @return the value of zcs_menu_info.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.create_date
     *
     * @param createDate the value for zcs_menu_info.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.create_time
     *
     * @return the value of zcs_menu_info.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.create_time
     *
     * @param createTime the value for zcs_menu_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.create_user
     *
     * @return the value of zcs_menu_info.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.create_user
     *
     * @param createUser the value for zcs_menu_info.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.update_date
     *
     * @return the value of zcs_menu_info.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.update_date
     *
     * @param updateDate the value for zcs_menu_info.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.update_time
     *
     * @return the value of zcs_menu_info.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.update_time
     *
     * @param updateTime the value for zcs_menu_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.update_user
     *
     * @return the value of zcs_menu_info.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.update_user
     *
     * @param updateUser the value for zcs_menu_info.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.time_stamp
     *
     * @return the value of zcs_menu_info.time_stamp
     *
     * @mbggenerated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.time_stamp
     *
     * @param timeStamp the value for zcs_menu_info.time_stamp
     *
     * @mbggenerated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcs_menu_info.rec_stat
     *
     * @return the value of zcs_menu_info.rec_stat
     *
     * @mbggenerated
     */
    public String getRecStat() {
        return recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcs_menu_info.rec_stat
     *
     * @param recStat the value for zcs_menu_info.rec_stat
     *
     * @mbggenerated
     */
    public void setRecStat(String recStat) {
        this.recStat = recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zcs_menu_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysMenuInfo other = (SysMenuInfo) that;
        return (this.getMenuCode() == null ? other.getMenuCode() == null : this.getMenuCode().equals(other.getMenuCode()))
            && (this.getMenuName() == null ? other.getMenuName() == null : this.getMenuName().equals(other.getMenuName()))
            && (this.getMenuLv() == null ? other.getMenuLv() == null : this.getMenuLv().equals(other.getMenuLv()))
            && (this.getNodePath() == null ? other.getNodePath() == null : this.getNodePath().equals(other.getNodePath()))
            && (this.getPareMenuCode() == null ? other.getPareMenuCode() == null : this.getPareMenuCode().equals(other.getPareMenuCode()))
            && (this.getPareMenu() == null ? other.getPareMenu() == null : this.getPareMenu().equals(other.getPareMenu()))
            && (this.getMenuOrder() == null ? other.getMenuOrder() == null : this.getMenuOrder().equals(other.getMenuOrder()))
            && (this.getMenuDesc() == null ? other.getMenuDesc() == null : this.getMenuDesc().equals(other.getMenuDesc()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getTimeStamp() == null ? other.getTimeStamp() == null : this.getTimeStamp().equals(other.getTimeStamp()))
            && (this.getRecStat() == null ? other.getRecStat() == null : this.getRecStat().equals(other.getRecStat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zcs_menu_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMenuCode() == null) ? 0 : getMenuCode().hashCode());
        result = prime * result + ((getMenuName() == null) ? 0 : getMenuName().hashCode());
        result = prime * result + ((getMenuLv() == null) ? 0 : getMenuLv().hashCode());
        result = prime * result + ((getNodePath() == null) ? 0 : getNodePath().hashCode());
        result = prime * result + ((getPareMenuCode() == null) ? 0 : getPareMenuCode().hashCode());
        result = prime * result + ((getPareMenu() == null) ? 0 : getPareMenu().hashCode());
        result = prime * result + ((getMenuOrder() == null) ? 0 : getMenuOrder().hashCode());
        result = prime * result + ((getMenuDesc() == null) ? 0 : getMenuDesc().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getTimeStamp() == null) ? 0 : getTimeStamp().hashCode());
        result = prime * result + ((getRecStat() == null) ? 0 : getRecStat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zcs_menu_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuCode=").append(menuCode);
        sb.append(", menuName=").append(menuName);
        sb.append(", menuLv=").append(menuLv);
        sb.append(", nodePath=").append(nodePath);
        sb.append(", pareMenuCode=").append(pareMenuCode);
        sb.append(", pareMenu=").append(pareMenu);
        sb.append(", menuOrder=").append(menuOrder);
        sb.append(", menuDesc=").append(menuDesc);
        sb.append(", createDate=").append(createDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", recStat=").append(recStat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}