package cn.com.zsyk.crm.manage.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class SysRuleCombineRule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.combine_rule_id
     *
     * @mbggenerated
     */
    private String combineRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.combine_rule_code
     *
     * @mbggenerated
     */
    private String combineRuleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.combine_rule_name
     *
     * @mbggenerated
     */
    private String combineRuleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.risk_feature
     *
     * @mbggenerated
     */
    private String riskFeature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.update_date
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.time_stamp
     *
     * @mbggenerated
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.rec_stat
     *
     * @mbggenerated
     */
    private String recStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.combine_expression
     *
     * @mbggenerated
     */
    private String combineExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_combine_rule.remark
     *
     * @mbggenerated
     */
    private String remark;

    private String isUsed;//是否被使用

    public String getIsUsed() {
        return isUsed;
    }

    public void setIsUsed(String isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_rule_combine_rule
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.combine_rule_id
     *
     * @return the value of sys_rule_combine_rule.combine_rule_id
     *
     * @mbggenerated
     */
    public String getCombineRuleId() {
        return combineRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.combine_rule_id
     *
     * @param combineRuleId the value for sys_rule_combine_rule.combine_rule_id
     *
     * @mbggenerated
     */
    public void setCombineRuleId(String combineRuleId) {
        this.combineRuleId = combineRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.combine_rule_code
     *
     * @return the value of sys_rule_combine_rule.combine_rule_code
     *
     * @mbggenerated
     */
    public String getCombineRuleCode() {
        return combineRuleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.combine_rule_code
     *
     * @param combineRuleCode the value for sys_rule_combine_rule.combine_rule_code
     *
     * @mbggenerated
     */
    public void setCombineRuleCode(String combineRuleCode) {
        this.combineRuleCode = combineRuleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.combine_rule_name
     *
     * @return the value of sys_rule_combine_rule.combine_rule_name
     *
     * @mbggenerated
     */
    public String getCombineRuleName() {
        return combineRuleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.combine_rule_name
     *
     * @param combineRuleName the value for sys_rule_combine_rule.combine_rule_name
     *
     * @mbggenerated
     */
    public void setCombineRuleName(String combineRuleName) {
        this.combineRuleName = combineRuleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.version
     *
     * @return the value of sys_rule_combine_rule.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.version
     *
     * @param version the value for sys_rule_combine_rule.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.risk_feature
     *
     * @return the value of sys_rule_combine_rule.risk_feature
     *
     * @mbggenerated
     */
    public String getRiskFeature() {
        return riskFeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.risk_feature
     *
     * @param riskFeature the value for sys_rule_combine_rule.risk_feature
     *
     * @mbggenerated
     */
    public void setRiskFeature(String riskFeature) {
        this.riskFeature = riskFeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.create_date
     *
     * @return the value of sys_rule_combine_rule.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.create_date
     *
     * @param createDate the value for sys_rule_combine_rule.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.create_time
     *
     * @return the value of sys_rule_combine_rule.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.create_time
     *
     * @param createTime the value for sys_rule_combine_rule.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.create_user
     *
     * @return the value of sys_rule_combine_rule.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.create_user
     *
     * @param createUser the value for sys_rule_combine_rule.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.update_date
     *
     * @return the value of sys_rule_combine_rule.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.update_date
     *
     * @param updateDate the value for sys_rule_combine_rule.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.update_time
     *
     * @return the value of sys_rule_combine_rule.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.update_time
     *
     * @param updateTime the value for sys_rule_combine_rule.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.update_user
     *
     * @return the value of sys_rule_combine_rule.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.update_user
     *
     * @param updateUser the value for sys_rule_combine_rule.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.time_stamp
     *
     * @return the value of sys_rule_combine_rule.time_stamp
     *
     * @mbggenerated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.time_stamp
     *
     * @param timeStamp the value for sys_rule_combine_rule.time_stamp
     *
     * @mbggenerated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.rec_stat
     *
     * @return the value of sys_rule_combine_rule.rec_stat
     *
     * @mbggenerated
     */
    public String getRecStat() {
        return recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.rec_stat
     *
     * @param recStat the value for sys_rule_combine_rule.rec_stat
     *
     * @mbggenerated
     */
    public void setRecStat(String recStat) {
        this.recStat = recStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.combine_expression
     *
     * @return the value of sys_rule_combine_rule.combine_expression
     *
     * @mbggenerated
     */
    public String getCombineExpression() {
        return combineExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.combine_expression
     *
     * @param combineExpression the value for sys_rule_combine_rule.combine_expression
     *
     * @mbggenerated
     */
    public void setCombineExpression(String combineExpression) {
        this.combineExpression = combineExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_combine_rule.remark
     *
     * @return the value of sys_rule_combine_rule.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_combine_rule.remark
     *
     * @param remark the value for sys_rule_combine_rule.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_combine_rule
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysRuleCombineRule other = (SysRuleCombineRule) that;
        return (this.getCombineRuleId() == null ? other.getCombineRuleId() == null : this.getCombineRuleId().equals(other.getCombineRuleId()))
            && (this.getCombineRuleCode() == null ? other.getCombineRuleCode() == null : this.getCombineRuleCode().equals(other.getCombineRuleCode()))
            && (this.getCombineRuleName() == null ? other.getCombineRuleName() == null : this.getCombineRuleName().equals(other.getCombineRuleName()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getRiskFeature() == null ? other.getRiskFeature() == null : this.getRiskFeature().equals(other.getRiskFeature()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getTimeStamp() == null ? other.getTimeStamp() == null : this.getTimeStamp().equals(other.getTimeStamp()))
            && (this.getRecStat() == null ? other.getRecStat() == null : this.getRecStat().equals(other.getRecStat()))
            && (this.getCombineExpression() == null ? other.getCombineExpression() == null : this.getCombineExpression().equals(other.getCombineExpression()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_combine_rule
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCombineRuleId() == null) ? 0 : getCombineRuleId().hashCode());
        result = prime * result + ((getCombineRuleCode() == null) ? 0 : getCombineRuleCode().hashCode());
        result = prime * result + ((getCombineRuleName() == null) ? 0 : getCombineRuleName().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getRiskFeature() == null) ? 0 : getRiskFeature().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getTimeStamp() == null) ? 0 : getTimeStamp().hashCode());
        result = prime * result + ((getRecStat() == null) ? 0 : getRecStat().hashCode());
        result = prime * result + ((getCombineExpression() == null) ? 0 : getCombineExpression().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_combine_rule
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", combineRuleId=").append(combineRuleId);
        sb.append(", combineRuleCode=").append(combineRuleCode);
        sb.append(", combineRuleName=").append(combineRuleName);
        sb.append(", version=").append(version);
        sb.append(", riskFeature=").append(riskFeature);
        sb.append(", createDate=").append(createDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", recStat=").append(recStat);
        sb.append(", combineExpression=").append(combineExpression);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }


    public List<SysRuleBaseRule> getBaseRules() {
		return BaseRules;
	}

	public void setBaseRules(List<SysRuleBaseRule> baseRules) {
		BaseRules = baseRules;
	}


	public List<SysRuleStrategy> getStrategys() {
		return strategys;
	}

	public void setStrategys(List<SysRuleStrategy> strategys) {
		this.strategys = strategys;
	}


	private List<SysRuleBaseRule> BaseRules;

    private List<SysRuleStrategy> strategys;


}