package cn.com.zsyk.crm.query.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

public class GSClientpermain implements Serializable {
    private String reportormobile;

    public String getReportormobile() {
        return reportormobile;
    }

    public void setReportormobile(String reportormobile) {
        this.reportormobile = reportormobile;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.CLIENTCODE
     *
     * @mbggenerated
     */
    private String clientcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.CLIENTCNAME
     *
     * @mbggenerated
     */
    private String clientcname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.CLIENTENAME
     *
     * @mbggenerated
     */
    private String clientename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.CLIENTTYPE
     *
     * @mbggenerated
     */
    private String clienttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.JOINDATE
     *
     * @mbggenerated
     */
    private Date joindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.BLACKLISTIND
     *
     * @mbggenerated
     */
    private String blacklistind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.FORMALIND
     *
     * @mbggenerated
     */
    private String formalind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.VIPIND
     *
     * @mbggenerated
     */
    private String vipind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.CANCELIND
     *
     * @mbggenerated
     */
    private String cancelind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.CANCELREASON
     *
     * @mbggenerated
     */
    private String cancelreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.CANCELDATE
     *
     * @mbggenerated
     */
    private Date canceldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.RELATEDCLIENT
     *
     * @mbggenerated
     */
    private String relatedclient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.FLAG
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.CONNECTION
     *
     * @mbggenerated
     */
    private String connection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.POSTCODE
     *
     * @mbggenerated
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.POSTADDRESS
     *
     * @mbggenerated
     */
    private String postaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.QUALITYIND
     *
     * @mbggenerated
     */
    private String qualityind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.CLIENTSTATUS
     *
     * @mbggenerated
     */
    private String clientstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.VISITIND
     *
     * @mbggenerated
     */
    private String visitind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.BANKCODE
     *
     * @mbggenerated
     */
    private String bankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.ACCOUNTNO
     *
     * @mbggenerated
     */
    private String accountno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.MONEYLAUNDERINGIND
     *
     * @mbggenerated
     */
    private String moneylaunderingind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.DIRECTCLIENTIND
     *
     * @mbggenerated
     */
    private String directclientind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.SCANDOCIND
     *
     * @mbggenerated
     */
    private String scandocind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.ORIGINCLIENTCODE
     *
     * @mbggenerated
     */
    private String originclientcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.RELATECLIENTCODE
     *
     * @mbggenerated
     */
    private String relateclientcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.CREATORCODE
     *
     * @mbggenerated
     */
    private String creatorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.UPDATERCODE
     *
     * @mbggenerated
     */
    private String updatercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.UPDATETIME
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.ITEMPROVINCECODE
     *
     * @mbggenerated
     */
    private String itemprovincecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.ITEMCITYCODE
     *
     * @mbggenerated
     */
    private String itemcitycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.ITEMPROVINCECNAME
     *
     * @mbggenerated
     */
    private String itemprovincecname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.ITEMCITYCNAME
     *
     * @mbggenerated
     */
    private String itemcitycname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.STARLEVEL
     *
     * @mbggenerated
     */
    private String starlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.SPECIALCLIENT
     *
     * @mbggenerated
     */
    private String specialclient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTMAIN.IDCARDVALIDITY
     *
     * @mbggenerated
     */
    private String idcardvalidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.ADDRESSCNAME
     *
     * @mbggenerated
     */
    private String addresscname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.ADDRESSENAME
     *
     * @mbggenerated
     */
    private String addressename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.IDENTIFYTYPE
     *
     * @mbggenerated
     */
    private String identifytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.IDENTIFYNUMBER
     *
     * @mbggenerated
     */
    private String identifynumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.ORIINALIDENTIFYNUMBER
     *
     * @mbggenerated
     */
    private String oriinalidentifynumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.BIRTHDATE
     *
     * @mbggenerated
     */
    private Date birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.COUNTRY_CODE
     *
     * @mbggenerated
     */
    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.NATIONALITY
     *
     * @mbggenerated
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.REGISTADDRESS
     *
     * @mbggenerated
     */
    private String registaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.REGINONCODE
     *
     * @mbggenerated
     */
    private String reginoncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.HOMEPLACE
     *
     * @mbggenerated
     */
    private String homeplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.MARRIAGE
     *
     * @mbggenerated
     */
    private String marriage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.LIVINGCITY
     *
     * @mbggenerated
     */
    private String livingcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.MARRIAGEDATE
     *
     * @mbggenerated
     */
    private Date marriagedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.GRADUATESCHOOL
     *
     * @mbggenerated
     */
    private String graduateschool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.EDUCATIONCODE
     *
     * @mbggenerated
     */
    private String educationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.MAJORCODE
     *
     * @mbggenerated
     */
    private String majorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.OCCUPATIONCODE
     *
     * @mbggenerated
     */
    private String occupationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.OCCUPATION
     *
     * @mbggenerated
     */
    private String occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.PARTTIMEJOBCODE
     *
     * @mbggenerated
     */
    private String parttimejobcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.PARTTIMEJOB
     *
     * @mbggenerated
     */
    private String parttimejob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.OCCUPATIONTYPE
     *
     * @mbggenerated
     */
    private String occupationtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.WORDRISKRANK
     *
     * @mbggenerated
     */
    private String wordriskrank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.UTIT
     *
     * @mbggenerated
     */
    private String utit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.UTITADDRESS
     *
     * @mbggenerated
     */
    private String utitaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.JOBATEA
     *
     * @mbggenerated
     */
    private String jobatea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.JOBDEPARTMENT
     *
     * @mbggenerated
     */
    private String jobdepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.OWNERSHIPCODE
     *
     * @mbggenerated
     */
    private String ownershipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.JOINCOMPANYDATE
     *
     * @mbggenerated
     */
    private Date joincompanydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.STARTWORKDATE
     *
     * @mbggenerated
     */
    private Date startworkdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.POSITION
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.TITLECODE
     *
     * @mbggenerated
     */
    private String titlecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.SALARY
     *
     * @mbggenerated
     */
    private BigDecimal salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.WORDTYPE
     *
     * @mbggenerated
     */
    private String wordtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.PLURALITYTYPE
     *
     * @mbggenerated
     */
    private String pluralitytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.CREDITLEVEL
     *
     * @mbggenerated
     */
    private String creditlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.CLIENTFLAG
     *
     * @mbggenerated
     */
    private String clientflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.PHONENUMBER
     *
     * @mbggenerated
     */
    private String phonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.FAX
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.MOBILE1
     *
     * @mbggenerated
     */
    private String mobile1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.LINKADDRESS
     *
     * @mbggenerated
     */
    private String linkaddress;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.PAGER
     *
     * @mbggenerated
     */
    private String pager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.EMAIL1
     *
     * @mbggenerated
     */
    private String email1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.RELATIONADDRESS1
     *
     * @mbggenerated
     */
    private String relationaddress1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.RELATIONADDRESS2
     *
     * @mbggenerated
     */
    private String relationaddress2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.RELATIONADDRESS3
     *
     * @mbggenerated
     */
    private String relationaddress3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.RELATIONADDRESS4
     *
     * @mbggenerated
     */
    private String relationaddress4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.HOMEPHONENUMBER
     *
     * @mbggenerated
     */
    private String homephonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.HOMEPOSTCODE
     *
     * @mbggenerated
     */
    private String homepostcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.HOMEADDRESS
     *
     * @mbggenerated
     */
    private String homeaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.WORKPHONENUMBER
     *
     * @mbggenerated
     */
    private String workphonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.COMPANYNAME
     *
     * @mbggenerated
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.SOCIALREGISTNUMBER
     *
     * @mbggenerated
     */
    private String socialregistnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.COMPANYKIND
     *
     * @mbggenerated
     */
    private String companykind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.WORKPOSTNUMBER
     *
     * @mbggenerated
     */
    private String workpostnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.WORKADDRESS1
     *
     * @mbggenerated
     */
    private String workaddress1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.WORKADDRESS2
     *
     * @mbggenerated
     */
    private String workaddress2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.WORKADDRESS3
     *
     * @mbggenerated
     */
    private String workaddress3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.WORKADDRESS4
     *
     * @mbggenerated
     */
    private String workaddress4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.OTHERADDRESS
     *
     * @mbggenerated
     */
    private String otheraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.OTHERPOSTCODE
     *
     * @mbggenerated
     */
    private String otherpostcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.OTHERRELATION
     *
     * @mbggenerated
     */
    private String otherrelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.NEWCLIENT
     *
     * @mbggenerated
     */
    private String newclient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.VALIDSTATUS
     *
     * @mbggenerated
     */
    private String validstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.ARTICLECODE
     *
     * @mbggenerated
     */
    private String articlecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.NETADDRESS
     *
     * @mbggenerated
     */
    private String netaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.LOWERVIEWFLAG
     *
     * @mbggenerated
     */
    private String lowerviewflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.FATHERCODE
     *
     * @mbggenerated
     */
    private String fathercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.HANDLERCODE
     *
     * @mbggenerated
     */
    private String handlercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.OPERATORCODE
     *
     * @mbggenerated
     */
    private String operatorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.INPUTDATE
     *
     * @mbggenerated
     */
    private Date inputdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.UPDATECODE
     *
     * @mbggenerated
     */
    private String updatecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.UPDATEDATE
     *
     * @mbggenerated
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.COMCODE
     *
     * @mbggenerated
     */
    private String comcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.DEATHDATE
     *
     * @mbggenerated
     */
    private Date deathdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.HEIGHT
     *
     * @mbggenerated
     */
    private Short height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.WEIGHT
     *
     * @mbggenerated
     */
    private Short weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.ACCIDENTSTATUS
     *
     * @mbggenerated
     */
    private String accidentstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.HEALTH
     *
     * @mbggenerated
     */
    private String health;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.SMOKEFLAG
     *
     * @mbggenerated
     */
    private String smokeflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.CTEDITGRADE
     *
     * @mbggenerated
     */
    private String cteditgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.ICNO
     *
     * @mbggenerated
     */
    private String icno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.PROTERTY
     *
     * @mbggenerated
     */
    private String proterty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.WEALTH
     *
     * @mbggenerated
     */
    private String wealth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.INCOME
     *
     * @mbggenerated
     */
    private Long income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.STATUS1
     *
     * @mbggenerated
     */
    private String status1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.MAKEDATE
     *
     * @mbggenerated
     */
    private Date makedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.MAKETIME
     *
     * @mbggenerated
     */
    private Date maketime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.HOUSEHOLDER
     *
     * @mbggenerated
     */
    private String householder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.HONORTITLE
     *
     * @mbggenerated
     */
    private String honortitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.SOCIALCODE
     *
     * @mbggenerated
     */
    private String socialcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.LANGUAGE
     *
     * @mbggenerated
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.DRIVINGLICENCEE
     *
     * @mbggenerated
     */
    private String drivinglicencee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.RETIRED
     *
     * @mbggenerated
     */
    private String retired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.SOCIALSECURITY
     *
     * @mbggenerated
     */
    private String socialsecurity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.BIRTHSECURITY
     *
     * @mbggenerated
     */
    private String birthsecurity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.MEDICARETYPE
     *
     * @mbggenerated
     */
    private String medicaretype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.MEDICARECITY
     *
     * @mbggenerated
     */
    private String medicarecity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.EMPLOYE
     *
     * @mbggenerated
     */
    private String employe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.EMPLOYEID
     *
     * @mbggenerated
     */
    private Long employeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.CLIENTGRADE
     *
     * @mbggenerated
     */
    private String clientgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.FOCUSTYPE
     *
     * @mbggenerated
     */
    private String focustype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.ADDIND
     *
     * @mbggenerated
     */
    private String addind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.IDENTIFYSTARTDATE
     *
     * @mbggenerated
     */
    private Date identifystartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.IDENTIFYENDDATE
     *
     * @mbggenerated
     */
    private Date identifyenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.GENERALLANGUAGE
     *
     * @mbggenerated
     */
    private String generallanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.CHANNELCODE
     *
     * @mbggenerated
     */
    private String channelcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.SURNAME
     *
     * @mbggenerated
     */
    private String surname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.MONIKER
     *
     * @mbggenerated
     */
    private String moniker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.FIRSTNAME
     *
     * @mbggenerated
     */
    private String firstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GSCLIENTPERSONA.LASTNAME
     *
     * @mbggenerated
     */
    private String lastname;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        GSClientpermain that = (GSClientpermain) o;
        return Objects.equals(clientcode, that.clientcode) &&
                Objects.equals(clientcname, that.clientcname) &&
                Objects.equals(clientename, that.clientename) &&
                Objects.equals(clienttype, that.clienttype) &&
                Objects.equals(joindate, that.joindate) &&
                Objects.equals(blacklistind, that.blacklistind) &&
                Objects.equals(formalind, that.formalind) &&
                Objects.equals(vipind, that.vipind) &&
                Objects.equals(cancelind, that.cancelind) &&
                Objects.equals(cancelreason, that.cancelreason) &&
                Objects.equals(canceldate, that.canceldate) &&
                Objects.equals(relatedclient, that.relatedclient) &&
                Objects.equals(remark, that.remark) &&
                Objects.equals(flag, that.flag) &&
                Objects.equals(connection, that.connection) &&
                Objects.equals(postcode, that.postcode) &&
                Objects.equals(postaddress, that.postaddress) &&
                Objects.equals(qualityind, that.qualityind) &&
                Objects.equals(clientstatus, that.clientstatus) &&
                Objects.equals(visitind, that.visitind) &&
                Objects.equals(bankcode, that.bankcode) &&
                Objects.equals(accountno, that.accountno) &&
                Objects.equals(moneylaunderingind, that.moneylaunderingind) &&
                Objects.equals(directclientind, that.directclientind) &&
                Objects.equals(scandocind, that.scandocind) &&
                Objects.equals(originclientcode, that.originclientcode) &&
                Objects.equals(relateclientcode, that.relateclientcode) &&
                Objects.equals(creatorcode, that.creatorcode) &&
                Objects.equals(createtime, that.createtime) &&
                Objects.equals(updatercode, that.updatercode) &&
                Objects.equals(updatetime, that.updatetime) &&
                Objects.equals(itemprovincecode, that.itemprovincecode) &&
                Objects.equals(itemcitycode, that.itemcitycode) &&
                Objects.equals(itemprovincecname, that.itemprovincecname) &&
                Objects.equals(itemcitycname, that.itemcitycname) &&
                Objects.equals(starlevel, that.starlevel) &&
                Objects.equals(specialclient, that.specialclient) &&
                Objects.equals(idcardvalidity, that.idcardvalidity) &&
                Objects.equals(addresscname, that.addresscname) &&
                Objects.equals(addressename, that.addressename) &&
                Objects.equals(identifytype, that.identifytype) &&
                Objects.equals(identifynumber, that.identifynumber) &&
                Objects.equals(oriinalidentifynumber, that.oriinalidentifynumber) &&
                Objects.equals(birthdate, that.birthdate) &&
                Objects.equals(countryCode, that.countryCode) &&
                Objects.equals(nationality, that.nationality) &&
                Objects.equals(registaddress, that.registaddress) &&
                Objects.equals(reginoncode, that.reginoncode) &&
                Objects.equals(homeplace, that.homeplace) &&
                Objects.equals(marriage, that.marriage) &&
                Objects.equals(livingcity, that.livingcity) &&
                Objects.equals(marriagedate, that.marriagedate) &&
                Objects.equals(sex, that.sex) &&
                Objects.equals(graduateschool, that.graduateschool) &&
                Objects.equals(educationcode, that.educationcode) &&
                Objects.equals(majorcode, that.majorcode) &&
                Objects.equals(occupationcode, that.occupationcode) &&
                Objects.equals(occupation, that.occupation) &&
                Objects.equals(parttimejobcode, that.parttimejobcode) &&
                Objects.equals(parttimejob, that.parttimejob) &&
                Objects.equals(occupationtype, that.occupationtype) &&
                Objects.equals(wordriskrank, that.wordriskrank) &&
                Objects.equals(utit, that.utit) &&
                Objects.equals(utitaddress, that.utitaddress) &&
                Objects.equals(jobatea, that.jobatea) &&
                Objects.equals(jobdepartment, that.jobdepartment) &&
                Objects.equals(ownershipcode, that.ownershipcode) &&
                Objects.equals(joincompanydate, that.joincompanydate) &&
                Objects.equals(startworkdate, that.startworkdate) &&
                Objects.equals(position, that.position) &&
                Objects.equals(titlecode, that.titlecode) &&
                Objects.equals(salary, that.salary) &&
                Objects.equals(wordtype, that.wordtype) &&
                Objects.equals(pluralitytype, that.pluralitytype) &&
                Objects.equals(creditlevel, that.creditlevel) &&
                Objects.equals(clientflag, that.clientflag) &&
                Objects.equals(phonenumber, that.phonenumber) &&
                Objects.equals(fax, that.fax) &&
                Objects.equals(mobile, that.mobile) &&
                Objects.equals(mobile1, that.mobile1) &&
                Objects.equals(linkaddress, that.linkaddress) &&
                Objects.equals(pager, that.pager) &&
                Objects.equals(email, that.email) &&
                Objects.equals(email1, that.email1) &&
                Objects.equals(relationaddress1, that.relationaddress1) &&
                Objects.equals(relationaddress2, that.relationaddress2) &&
                Objects.equals(relationaddress3, that.relationaddress3) &&
                Objects.equals(relationaddress4, that.relationaddress4) &&
                Objects.equals(homephonenumber, that.homephonenumber) &&
                Objects.equals(homepostcode, that.homepostcode) &&
                Objects.equals(homeaddress, that.homeaddress) &&
                Objects.equals(workphonenumber, that.workphonenumber) &&
                Objects.equals(companyname, that.companyname) &&
                Objects.equals(socialregistnumber, that.socialregistnumber) &&
                Objects.equals(companykind, that.companykind) &&
                Objects.equals(workpostnumber, that.workpostnumber) &&
                Objects.equals(workaddress1, that.workaddress1) &&
                Objects.equals(workaddress2, that.workaddress2) &&
                Objects.equals(workaddress3, that.workaddress3) &&
                Objects.equals(workaddress4, that.workaddress4) &&
                Objects.equals(otheraddress, that.otheraddress) &&
                Objects.equals(otherpostcode, that.otherpostcode) &&
                Objects.equals(otherrelation, that.otherrelation) &&
                Objects.equals(newclient, that.newclient) &&
                Objects.equals(validstatus, that.validstatus) &&
                Objects.equals(articlecode, that.articlecode) &&
                Objects.equals(netaddress, that.netaddress) &&
                Objects.equals(lowerviewflag, that.lowerviewflag) &&
                Objects.equals(fathercode, that.fathercode) &&
                Objects.equals(handlercode, that.handlercode) &&
                Objects.equals(operatorcode, that.operatorcode) &&
                Objects.equals(inputdate, that.inputdate) &&
                Objects.equals(updatecode, that.updatecode) &&
                Objects.equals(updatedate, that.updatedate) &&
                Objects.equals(comcode, that.comcode) &&
                Objects.equals(deathdate, that.deathdate) &&
                Objects.equals(height, that.height) &&
                Objects.equals(weight, that.weight) &&
                Objects.equals(accidentstatus, that.accidentstatus) &&
                Objects.equals(health, that.health) &&
                Objects.equals(smokeflag, that.smokeflag) &&
                Objects.equals(cteditgrade, that.cteditgrade) &&
                Objects.equals(icno, that.icno) &&
                Objects.equals(proterty, that.proterty) &&
                Objects.equals(wealth, that.wealth) &&
                Objects.equals(income, that.income) &&
                Objects.equals(status1, that.status1) &&
                Objects.equals(makedate, that.makedate) &&
                Objects.equals(maketime, that.maketime) &&
                Objects.equals(householder, that.householder) &&
                Objects.equals(honortitle, that.honortitle) &&
                Objects.equals(socialcode, that.socialcode) &&
                Objects.equals(language, that.language) &&
                Objects.equals(drivinglicencee, that.drivinglicencee) &&
                Objects.equals(retired, that.retired) &&
                Objects.equals(socialsecurity, that.socialsecurity) &&
                Objects.equals(birthsecurity, that.birthsecurity) &&
                Objects.equals(medicaretype, that.medicaretype) &&
                Objects.equals(medicarecity, that.medicarecity) &&
                Objects.equals(employe, that.employe) &&
                Objects.equals(employeid, that.employeid) &&
                Objects.equals(clientgrade, that.clientgrade) &&
                Objects.equals(focustype, that.focustype) &&
                Objects.equals(status, that.status) &&
                Objects.equals(addind, that.addind) &&
                Objects.equals(identifystartdate, that.identifystartdate) &&
                Objects.equals(identifyenddate, that.identifyenddate) &&
                Objects.equals(generallanguage, that.generallanguage) &&
                Objects.equals(channelcode, that.channelcode) &&
                Objects.equals(surname, that.surname) &&
                Objects.equals(moniker, that.moniker) &&
                Objects.equals(firstname, that.firstname) &&
                Objects.equals(lastname, that.lastname);
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientcode, clientcname, clientename, clienttype, joindate, blacklistind, formalind, vipind, cancelind, cancelreason, canceldate, relatedclient, remark, flag, connection, postcode, postaddress, qualityind, clientstatus, visitind, bankcode, accountno, moneylaunderingind, directclientind, scandocind, originclientcode, relateclientcode, creatorcode, createtime, updatercode, updatetime, itemprovincecode, itemcitycode, itemprovincecname, itemcitycname, starlevel, specialclient, idcardvalidity, addresscname, addressename, identifytype, identifynumber, oriinalidentifynumber, birthdate, countryCode, nationality, registaddress, reginoncode, homeplace, marriage, livingcity, marriagedate, sex, graduateschool, educationcode, majorcode, occupationcode, occupation, parttimejobcode, parttimejob, occupationtype, wordriskrank, utit, utitaddress, jobatea, jobdepartment, ownershipcode, joincompanydate, startworkdate, position, titlecode, salary, wordtype, pluralitytype, creditlevel, clientflag, phonenumber, fax, mobile, mobile1, linkaddress, pager, email, email1, relationaddress1, relationaddress2, relationaddress3, relationaddress4, homephonenumber, homepostcode, homeaddress, workphonenumber, companyname, socialregistnumber, companykind, workpostnumber, workaddress1, workaddress2, workaddress3, workaddress4, otheraddress, otherpostcode, otherrelation, newclient, validstatus, articlecode, netaddress, lowerviewflag, fathercode, handlercode, operatorcode, inputdate, updatecode, updatedate, comcode, deathdate, height, weight, accidentstatus, health, smokeflag, cteditgrade, icno, proterty, wealth, income, status1, makedate, maketime, householder, honortitle, socialcode, language, drivinglicencee, retired, socialsecurity, birthsecurity, medicaretype, medicarecity, employe, employeid, clientgrade, focustype, status, addind, identifystartdate, identifyenddate, generallanguage, channelcode, surname, moniker, firstname, lastname);
    }

    @Override
    public String toString() {
        return "GSClientpermain{" +
                "clientcode='" + clientcode + '\'' +
                ", clientcname='" + clientcname + '\'' +
                ", clientename='" + clientename + '\'' +
                ", clienttype='" + clienttype + '\'' +
                ", joindate=" + joindate +
                ", blacklistind='" + blacklistind + '\'' +
                ", formalind='" + formalind + '\'' +
                ", vipind='" + vipind + '\'' +
                ", cancelind='" + cancelind + '\'' +
                ", cancelreason='" + cancelreason + '\'' +
                ", canceldate=" + canceldate +
                ", relatedclient='" + relatedclient + '\'' +
                ", remark='" + remark + '\'' +
                ", flag='" + flag + '\'' +
                ", connection='" + connection + '\'' +
                ", postcode='" + postcode + '\'' +
                ", postaddress='" + postaddress + '\'' +
                ", qualityind='" + qualityind + '\'' +
                ", clientstatus='" + clientstatus + '\'' +
                ", visitind='" + visitind + '\'' +
                ", bankcode='" + bankcode + '\'' +
                ", accountno='" + accountno + '\'' +
                ", moneylaunderingind='" + moneylaunderingind + '\'' +
                ", directclientind='" + directclientind + '\'' +
                ", scandocind='" + scandocind + '\'' +
                ", originclientcode='" + originclientcode + '\'' +
                ", relateclientcode='" + relateclientcode + '\'' +
                ", creatorcode='" + creatorcode + '\'' +
                ", createtime=" + createtime +
                ", updatercode='" + updatercode + '\'' +
                ", updatetime=" + updatetime +
                ", itemprovincecode='" + itemprovincecode + '\'' +
                ", itemcitycode='" + itemcitycode + '\'' +
                ", itemprovincecname='" + itemprovincecname + '\'' +
                ", itemcitycname='" + itemcitycname + '\'' +
                ", starlevel='" + starlevel + '\'' +
                ", specialclient='" + specialclient + '\'' +
                ", idcardvalidity='" + idcardvalidity + '\'' +
                ", addresscname='" + addresscname + '\'' +
                ", addressename='" + addressename + '\'' +
                ", identifytype='" + identifytype + '\'' +
                ", identifynumber='" + identifynumber + '\'' +
                ", oriinalidentifynumber='" + oriinalidentifynumber + '\'' +
                ", birthdate=" + birthdate +
                ", countryCode='" + countryCode + '\'' +
                ", nationality='" + nationality + '\'' +
                ", registaddress='" + registaddress + '\'' +
                ", reginoncode='" + reginoncode + '\'' +
                ", homeplace='" + homeplace + '\'' +
                ", marriage='" + marriage + '\'' +
                ", livingcity='" + livingcity + '\'' +
                ", marriagedate=" + marriagedate +
                ", sex='" + sex + '\'' +
                ", graduateschool='" + graduateschool + '\'' +
                ", educationcode='" + educationcode + '\'' +
                ", majorcode='" + majorcode + '\'' +
                ", occupationcode='" + occupationcode + '\'' +
                ", occupation='" + occupation + '\'' +
                ", parttimejobcode='" + parttimejobcode + '\'' +
                ", parttimejob='" + parttimejob + '\'' +
                ", occupationtype='" + occupationtype + '\'' +
                ", wordriskrank='" + wordriskrank + '\'' +
                ", utit='" + utit + '\'' +
                ", utitaddress='" + utitaddress + '\'' +
                ", jobatea='" + jobatea + '\'' +
                ", jobdepartment='" + jobdepartment + '\'' +
                ", ownershipcode='" + ownershipcode + '\'' +
                ", joincompanydate=" + joincompanydate +
                ", startworkdate=" + startworkdate +
                ", position='" + position + '\'' +
                ", titlecode='" + titlecode + '\'' +
                ", salary=" + salary +
                ", wordtype='" + wordtype + '\'' +
                ", pluralitytype='" + pluralitytype + '\'' +
                ", creditlevel='" + creditlevel + '\'' +
                ", clientflag='" + clientflag + '\'' +
                ", phonenumber='" + phonenumber + '\'' +
                ", fax='" + fax + '\'' +
                ", mobile='" + mobile + '\'' +
                ", mobile1='" + mobile1 + '\'' +
                ", linkaddress='" + linkaddress + '\'' +
                ", pager='" + pager + '\'' +
                ", email='" + email + '\'' +
                ", email1='" + email1 + '\'' +
                ", relationaddress1='" + relationaddress1 + '\'' +
                ", relationaddress2='" + relationaddress2 + '\'' +
                ", relationaddress3='" + relationaddress3 + '\'' +
                ", relationaddress4='" + relationaddress4 + '\'' +
                ", homephonenumber='" + homephonenumber + '\'' +
                ", homepostcode='" + homepostcode + '\'' +
                ", homeaddress='" + homeaddress + '\'' +
                ", workphonenumber='" + workphonenumber + '\'' +
                ", companyname='" + companyname + '\'' +
                ", socialregistnumber='" + socialregistnumber + '\'' +
                ", companykind='" + companykind + '\'' +
                ", workpostnumber='" + workpostnumber + '\'' +
                ", workaddress1='" + workaddress1 + '\'' +
                ", workaddress2='" + workaddress2 + '\'' +
                ", workaddress3='" + workaddress3 + '\'' +
                ", workaddress4='" + workaddress4 + '\'' +
                ", otheraddress='" + otheraddress + '\'' +
                ", otherpostcode='" + otherpostcode + '\'' +
                ", otherrelation='" + otherrelation + '\'' +
                ", newclient='" + newclient + '\'' +
                ", validstatus='" + validstatus + '\'' +
                ", articlecode='" + articlecode + '\'' +
                ", netaddress='" + netaddress + '\'' +
                ", lowerviewflag='" + lowerviewflag + '\'' +
                ", fathercode='" + fathercode + '\'' +
                ", handlercode='" + handlercode + '\'' +
                ", operatorcode='" + operatorcode + '\'' +
                ", inputdate=" + inputdate +
                ", updatecode='" + updatecode + '\'' +
                ", updatedate=" + updatedate +
                ", comcode='" + comcode + '\'' +
                ", deathdate=" + deathdate +
                ", height=" + height +
                ", weight=" + weight +
                ", accidentstatus='" + accidentstatus + '\'' +
                ", health='" + health + '\'' +
                ", smokeflag='" + smokeflag + '\'' +
                ", cteditgrade='" + cteditgrade + '\'' +
                ", icno='" + icno + '\'' +
                ", proterty='" + proterty + '\'' +
                ", wealth='" + wealth + '\'' +
                ", income=" + income +
                ", status1='" + status1 + '\'' +
                ", makedate=" + makedate +
                ", maketime=" + maketime +
                ", householder='" + householder + '\'' +
                ", honortitle='" + honortitle + '\'' +
                ", socialcode='" + socialcode + '\'' +
                ", language='" + language + '\'' +
                ", drivinglicencee='" + drivinglicencee + '\'' +
                ", retired='" + retired + '\'' +
                ", socialsecurity='" + socialsecurity + '\'' +
                ", birthsecurity='" + birthsecurity + '\'' +
                ", medicaretype='" + medicaretype + '\'' +
                ", medicarecity='" + medicarecity + '\'' +
                ", employe='" + employe + '\'' +
                ", employeid=" + employeid +
                ", clientgrade='" + clientgrade + '\'' +
                ", focustype='" + focustype + '\'' +
                ", status='" + status + '\'' +
                ", addind='" + addind + '\'' +
                ", identifystartdate=" + identifystartdate +
                ", identifyenddate=" + identifyenddate +
                ", generallanguage='" + generallanguage + '\'' +
                ", channelcode='" + channelcode + '\'' +
                ", surname='" + surname + '\'' +
                ", moniker='" + moniker + '\'' +
                ", firstname='" + firstname + '\'' +
                ", lastname='" + lastname + '\'' +
                '}';
    }

    public String getClientcode() {
        return clientcode;
    }

    public void setClientcode(String clientcode) {
        this.clientcode = clientcode;
    }

    public String getClientcname() {
        return clientcname;
    }

    public void setClientcname(String clientcname) {
        this.clientcname = clientcname;
    }

    public String getClientename() {
        return clientename;
    }

    public void setClientename(String clientename) {
        this.clientename = clientename;
    }

    public String getClienttype() {
        return clienttype;
    }

    public void setClienttype(String clienttype) {
        this.clienttype = clienttype;
    }

    public Date getJoindate() {
        return joindate;
    }

    public void setJoindate(Date joindate) {
        this.joindate = joindate;
    }

    public String getBlacklistind() {
        return blacklistind;
    }

    public void setBlacklistind(String blacklistind) {
        this.blacklistind = blacklistind;
    }

    public String getFormalind() {
        return formalind;
    }

    public void setFormalind(String formalind) {
        this.formalind = formalind;
    }

    public String getVipind() {
        return vipind;
    }

    public void setVipind(String vipind) {
        this.vipind = vipind;
    }

    public String getCancelind() {
        return cancelind;
    }

    public void setCancelind(String cancelind) {
        this.cancelind = cancelind;
    }

    public String getCancelreason() {
        return cancelreason;
    }

    public void setCancelreason(String cancelreason) {
        this.cancelreason = cancelreason;
    }

    public Date getCanceldate() {
        return canceldate;
    }

    public void setCanceldate(Date canceldate) {
        this.canceldate = canceldate;
    }

    public String getRelatedclient() {
        return relatedclient;
    }

    public void setRelatedclient(String relatedclient) {
        this.relatedclient = relatedclient;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getFlag() {
        return flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public String getConnection() {
        return connection;
    }

    public void setConnection(String connection) {
        this.connection = connection;
    }

    public String getPostcode() {
        return postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getPostaddress() {
        return postaddress;
    }

    public void setPostaddress(String postaddress) {
        this.postaddress = postaddress;
    }

    public String getQualityind() {
        return qualityind;
    }

    public void setQualityind(String qualityind) {
        this.qualityind = qualityind;
    }

    public String getClientstatus() {
        return clientstatus;
    }

    public void setClientstatus(String clientstatus) {
        this.clientstatus = clientstatus;
    }

    public String getVisitind() {
        return visitind;
    }

    public void setVisitind(String visitind) {
        this.visitind = visitind;
    }

    public String getBankcode() {
        return bankcode;
    }

    public void setBankcode(String bankcode) {
        this.bankcode = bankcode;
    }

    public String getAccountno() {
        return accountno;
    }

    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }

    public String getMoneylaunderingind() {
        return moneylaunderingind;
    }

    public void setMoneylaunderingind(String moneylaunderingind) {
        this.moneylaunderingind = moneylaunderingind;
    }

    public String getDirectclientind() {
        return directclientind;
    }

    public void setDirectclientind(String directclientind) {
        this.directclientind = directclientind;
    }

    public String getScandocind() {
        return scandocind;
    }

    public void setScandocind(String scandocind) {
        this.scandocind = scandocind;
    }

    public String getOriginclientcode() {
        return originclientcode;
    }

    public void setOriginclientcode(String originclientcode) {
        this.originclientcode = originclientcode;
    }

    public String getRelateclientcode() {
        return relateclientcode;
    }

    public void setRelateclientcode(String relateclientcode) {
        this.relateclientcode = relateclientcode;
    }

    public String getCreatorcode() {
        return creatorcode;
    }

    public void setCreatorcode(String creatorcode) {
        this.creatorcode = creatorcode;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public String getUpdatercode() {
        return updatercode;
    }

    public void setUpdatercode(String updatercode) {
        this.updatercode = updatercode;
    }

    public Date getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public String getItemprovincecode() {
        return itemprovincecode;
    }

    public void setItemprovincecode(String itemprovincecode) {
        this.itemprovincecode = itemprovincecode;
    }

    public String getItemcitycode() {
        return itemcitycode;
    }

    public void setItemcitycode(String itemcitycode) {
        this.itemcitycode = itemcitycode;
    }

    public String getItemprovincecname() {
        return itemprovincecname;
    }

    public void setItemprovincecname(String itemprovincecname) {
        this.itemprovincecname = itemprovincecname;
    }

    public String getItemcitycname() {
        return itemcitycname;
    }

    public void setItemcitycname(String itemcitycname) {
        this.itemcitycname = itemcitycname;
    }

    public String getStarlevel() {
        return starlevel;
    }

    public void setStarlevel(String starlevel) {
        this.starlevel = starlevel;
    }

    public String getSpecialclient() {
        return specialclient;
    }

    public void setSpecialclient(String specialclient) {
        this.specialclient = specialclient;
    }

    public String getIdcardvalidity() {
        return idcardvalidity;
    }

    public void setIdcardvalidity(String idcardvalidity) {
        this.idcardvalidity = idcardvalidity;
    }

    public String getAddresscname() {
        return addresscname;
    }

    public void setAddresscname(String addresscname) {
        this.addresscname = addresscname;
    }

    public String getAddressename() {
        return addressename;
    }

    public void setAddressename(String addressename) {
        this.addressename = addressename;
    }

    public String getIdentifytype() {
        return identifytype;
    }

    public void setIdentifytype(String identifytype) {
        this.identifytype = identifytype;
    }

    public String getIdentifynumber() {
        return identifynumber;
    }

    public void setIdentifynumber(String identifynumber) {
        this.identifynumber = identifynumber;
    }

    public String getOriinalidentifynumber() {
        return oriinalidentifynumber;
    }

    public void setOriinalidentifynumber(String oriinalidentifynumber) {
        this.oriinalidentifynumber = oriinalidentifynumber;
    }

    public Date getBirthdate() {
        return birthdate;
    }

    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public String getNationality() {
        return nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public String getRegistaddress() {
        return registaddress;
    }

    public void setRegistaddress(String registaddress) {
        this.registaddress = registaddress;
    }

    public String getReginoncode() {
        return reginoncode;
    }

    public void setReginoncode(String reginoncode) {
        this.reginoncode = reginoncode;
    }

    public String getHomeplace() {
        return homeplace;
    }

    public void setHomeplace(String homeplace) {
        this.homeplace = homeplace;
    }

    public String getMarriage() {
        return marriage;
    }

    public void setMarriage(String marriage) {
        this.marriage = marriage;
    }

    public String getLivingcity() {
        return livingcity;
    }

    public void setLivingcity(String livingcity) {
        this.livingcity = livingcity;
    }

    public Date getMarriagedate() {
        return marriagedate;
    }

    public void setMarriagedate(Date marriagedate) {
        this.marriagedate = marriagedate;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getGraduateschool() {
        return graduateschool;
    }

    public void setGraduateschool(String graduateschool) {
        this.graduateschool = graduateschool;
    }

    public String getEducationcode() {
        return educationcode;
    }

    public void setEducationcode(String educationcode) {
        this.educationcode = educationcode;
    }

    public String getMajorcode() {
        return majorcode;
    }

    public void setMajorcode(String majorcode) {
        this.majorcode = majorcode;
    }

    public String getOccupationcode() {
        return occupationcode;
    }

    public void setOccupationcode(String occupationcode) {
        this.occupationcode = occupationcode;
    }

    public String getOccupation() {
        return occupation;
    }

    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    public String getParttimejobcode() {
        return parttimejobcode;
    }

    public void setParttimejobcode(String parttimejobcode) {
        this.parttimejobcode = parttimejobcode;
    }

    public String getParttimejob() {
        return parttimejob;
    }

    public void setParttimejob(String parttimejob) {
        this.parttimejob = parttimejob;
    }

    public String getOccupationtype() {
        return occupationtype;
    }

    public void setOccupationtype(String occupationtype) {
        this.occupationtype = occupationtype;
    }

    public String getWordriskrank() {
        return wordriskrank;
    }

    public void setWordriskrank(String wordriskrank) {
        this.wordriskrank = wordriskrank;
    }

    public String getUtit() {
        return utit;
    }

    public void setUtit(String utit) {
        this.utit = utit;
    }

    public String getUtitaddress() {
        return utitaddress;
    }

    public void setUtitaddress(String utitaddress) {
        this.utitaddress = utitaddress;
    }

    public String getJobatea() {
        return jobatea;
    }

    public void setJobatea(String jobatea) {
        this.jobatea = jobatea;
    }

    public String getJobdepartment() {
        return jobdepartment;
    }

    public void setJobdepartment(String jobdepartment) {
        this.jobdepartment = jobdepartment;
    }

    public String getOwnershipcode() {
        return ownershipcode;
    }

    public void setOwnershipcode(String ownershipcode) {
        this.ownershipcode = ownershipcode;
    }

    public Date getJoincompanydate() {
        return joincompanydate;
    }

    public void setJoincompanydate(Date joincompanydate) {
        this.joincompanydate = joincompanydate;
    }

    public Date getStartworkdate() {
        return startworkdate;
    }

    public void setStartworkdate(Date startworkdate) {
        this.startworkdate = startworkdate;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getTitlecode() {
        return titlecode;
    }

    public void setTitlecode(String titlecode) {
        this.titlecode = titlecode;
    }

    public BigDecimal getSalary() {
        return salary;
    }

    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    public String getWordtype() {
        return wordtype;
    }

    public void setWordtype(String wordtype) {
        this.wordtype = wordtype;
    }

    public String getPluralitytype() {
        return pluralitytype;
    }

    public void setPluralitytype(String pluralitytype) {
        this.pluralitytype = pluralitytype;
    }

    public String getCreditlevel() {
        return creditlevel;
    }

    public void setCreditlevel(String creditlevel) {
        this.creditlevel = creditlevel;
    }

    public String getClientflag() {
        return clientflag;
    }

    public void setClientflag(String clientflag) {
        this.clientflag = clientflag;
    }

    public String getPhonenumber() {
        return phonenumber;
    }

    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    public String getFax() {
        return fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getMobile1() {
        return mobile1;
    }

    public void setMobile1(String mobile1) {
        this.mobile1 = mobile1;
    }

    public String getLinkaddress() {
        return linkaddress;
    }

    public void setLinkaddress(String linkaddress) {
        this.linkaddress = linkaddress;
    }

    public String getPager() {
        return pager;
    }

    public void setPager(String pager) {
        this.pager = pager;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail1() {
        return email1;
    }

    public void setEmail1(String email1) {
        this.email1 = email1;
    }

    public String getRelationaddress1() {
        return relationaddress1;
    }

    public void setRelationaddress1(String relationaddress1) {
        this.relationaddress1 = relationaddress1;
    }

    public String getRelationaddress2() {
        return relationaddress2;
    }

    public void setRelationaddress2(String relationaddress2) {
        this.relationaddress2 = relationaddress2;
    }

    public String getRelationaddress3() {
        return relationaddress3;
    }

    public void setRelationaddress3(String relationaddress3) {
        this.relationaddress3 = relationaddress3;
    }

    public String getRelationaddress4() {
        return relationaddress4;
    }

    public void setRelationaddress4(String relationaddress4) {
        this.relationaddress4 = relationaddress4;
    }

    public String getHomephonenumber() {
        return homephonenumber;
    }

    public void setHomephonenumber(String homephonenumber) {
        this.homephonenumber = homephonenumber;
    }

    public String getHomepostcode() {
        return homepostcode;
    }

    public void setHomepostcode(String homepostcode) {
        this.homepostcode = homepostcode;
    }

    public String getHomeaddress() {
        return homeaddress;
    }

    public void setHomeaddress(String homeaddress) {
        this.homeaddress = homeaddress;
    }

    public String getWorkphonenumber() {
        return workphonenumber;
    }

    public void setWorkphonenumber(String workphonenumber) {
        this.workphonenumber = workphonenumber;
    }

    public String getCompanyname() {
        return companyname;
    }

    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    public String getSocialregistnumber() {
        return socialregistnumber;
    }

    public void setSocialregistnumber(String socialregistnumber) {
        this.socialregistnumber = socialregistnumber;
    }

    public String getCompanykind() {
        return companykind;
    }

    public void setCompanykind(String companykind) {
        this.companykind = companykind;
    }

    public String getWorkpostnumber() {
        return workpostnumber;
    }

    public void setWorkpostnumber(String workpostnumber) {
        this.workpostnumber = workpostnumber;
    }

    public String getWorkaddress1() {
        return workaddress1;
    }

    public void setWorkaddress1(String workaddress1) {
        this.workaddress1 = workaddress1;
    }

    public String getWorkaddress2() {
        return workaddress2;
    }

    public void setWorkaddress2(String workaddress2) {
        this.workaddress2 = workaddress2;
    }

    public String getWorkaddress3() {
        return workaddress3;
    }

    public void setWorkaddress3(String workaddress3) {
        this.workaddress3 = workaddress3;
    }

    public String getWorkaddress4() {
        return workaddress4;
    }

    public void setWorkaddress4(String workaddress4) {
        this.workaddress4 = workaddress4;
    }

    public String getOtheraddress() {
        return otheraddress;
    }

    public void setOtheraddress(String otheraddress) {
        this.otheraddress = otheraddress;
    }

    public String getOtherpostcode() {
        return otherpostcode;
    }

    public void setOtherpostcode(String otherpostcode) {
        this.otherpostcode = otherpostcode;
    }

    public String getOtherrelation() {
        return otherrelation;
    }

    public void setOtherrelation(String otherrelation) {
        this.otherrelation = otherrelation;
    }

    public String getNewclient() {
        return newclient;
    }

    public void setNewclient(String newclient) {
        this.newclient = newclient;
    }

    public String getValidstatus() {
        return validstatus;
    }

    public void setValidstatus(String validstatus) {
        this.validstatus = validstatus;
    }

    public String getArticlecode() {
        return articlecode;
    }

    public void setArticlecode(String articlecode) {
        this.articlecode = articlecode;
    }

    public String getNetaddress() {
        return netaddress;
    }

    public void setNetaddress(String netaddress) {
        this.netaddress = netaddress;
    }

    public String getLowerviewflag() {
        return lowerviewflag;
    }

    public void setLowerviewflag(String lowerviewflag) {
        this.lowerviewflag = lowerviewflag;
    }

    public String getFathercode() {
        return fathercode;
    }

    public void setFathercode(String fathercode) {
        this.fathercode = fathercode;
    }

    public String getHandlercode() {
        return handlercode;
    }

    public void setHandlercode(String handlercode) {
        this.handlercode = handlercode;
    }

    public String getOperatorcode() {
        return operatorcode;
    }

    public void setOperatorcode(String operatorcode) {
        this.operatorcode = operatorcode;
    }

    public Date getInputdate() {
        return inputdate;
    }

    public void setInputdate(Date inputdate) {
        this.inputdate = inputdate;
    }

    public String getUpdatecode() {
        return updatecode;
    }

    public void setUpdatecode(String updatecode) {
        this.updatecode = updatecode;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public String getComcode() {
        return comcode;
    }

    public void setComcode(String comcode) {
        this.comcode = comcode;
    }

    public Date getDeathdate() {
        return deathdate;
    }

    public void setDeathdate(Date deathdate) {
        this.deathdate = deathdate;
    }

    public Short getHeight() {
        return height;
    }

    public void setHeight(Short height) {
        this.height = height;
    }

    public Short getWeight() {
        return weight;
    }

    public void setWeight(Short weight) {
        this.weight = weight;
    }

    public String getAccidentstatus() {
        return accidentstatus;
    }

    public void setAccidentstatus(String accidentstatus) {
        this.accidentstatus = accidentstatus;
    }

    public String getHealth() {
        return health;
    }

    public void setHealth(String health) {
        this.health = health;
    }

    public String getSmokeflag() {
        return smokeflag;
    }

    public void setSmokeflag(String smokeflag) {
        this.smokeflag = smokeflag;
    }

    public String getCteditgrade() {
        return cteditgrade;
    }

    public void setCteditgrade(String cteditgrade) {
        this.cteditgrade = cteditgrade;
    }

    public String getIcno() {
        return icno;
    }

    public void setIcno(String icno) {
        this.icno = icno;
    }

    public String getProterty() {
        return proterty;
    }

    public void setProterty(String proterty) {
        this.proterty = proterty;
    }

    public String getWealth() {
        return wealth;
    }

    public void setWealth(String wealth) {
        this.wealth = wealth;
    }

    public Long getIncome() {
        return income;
    }

    public void setIncome(Long income) {
        this.income = income;
    }

    public String getStatus1() {
        return status1;
    }

    public void setStatus1(String status1) {
        this.status1 = status1;
    }

    public Date getMakedate() {
        return makedate;
    }

    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }

    public Date getMaketime() {
        return maketime;
    }

    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    public String getHouseholder() {
        return householder;
    }

    public void setHouseholder(String householder) {
        this.householder = householder;
    }

    public String getHonortitle() {
        return honortitle;
    }

    public void setHonortitle(String honortitle) {
        this.honortitle = honortitle;
    }

    public String getSocialcode() {
        return socialcode;
    }

    public void setSocialcode(String socialcode) {
        this.socialcode = socialcode;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getDrivinglicencee() {
        return drivinglicencee;
    }

    public void setDrivinglicencee(String drivinglicencee) {
        this.drivinglicencee = drivinglicencee;
    }

    public String getRetired() {
        return retired;
    }

    public void setRetired(String retired) {
        this.retired = retired;
    }

    public String getSocialsecurity() {
        return socialsecurity;
    }

    public void setSocialsecurity(String socialsecurity) {
        this.socialsecurity = socialsecurity;
    }

    public String getBirthsecurity() {
        return birthsecurity;
    }

    public void setBirthsecurity(String birthsecurity) {
        this.birthsecurity = birthsecurity;
    }

    public String getMedicaretype() {
        return medicaretype;
    }

    public void setMedicaretype(String medicaretype) {
        this.medicaretype = medicaretype;
    }

    public String getMedicarecity() {
        return medicarecity;
    }

    public void setMedicarecity(String medicarecity) {
        this.medicarecity = medicarecity;
    }

    public String getEmploye() {
        return employe;
    }

    public void setEmploye(String employe) {
        this.employe = employe;
    }

    public Long getEmployeid() {
        return employeid;
    }

    public void setEmployeid(Long employeid) {
        this.employeid = employeid;
    }

    public String getClientgrade() {
        return clientgrade;
    }

    public void setClientgrade(String clientgrade) {
        this.clientgrade = clientgrade;
    }

    public String getFocustype() {
        return focustype;
    }

    public void setFocustype(String focustype) {
        this.focustype = focustype;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getAddind() {
        return addind;
    }

    public void setAddind(String addind) {
        this.addind = addind;
    }

    public Date getIdentifystartdate() {
        return identifystartdate;
    }

    public void setIdentifystartdate(Date identifystartdate) {
        this.identifystartdate = identifystartdate;
    }

    public Date getIdentifyenddate() {
        return identifyenddate;
    }

    public void setIdentifyenddate(Date identifyenddate) {
        this.identifyenddate = identifyenddate;
    }

    public String getGenerallanguage() {
        return generallanguage;
    }

    public void setGenerallanguage(String generallanguage) {
        this.generallanguage = generallanguage;
    }

    public String getChannelcode() {
        return channelcode;
    }

    public void setChannelcode(String channelcode) {
        this.channelcode = channelcode;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getMoniker() {
        return moniker;
    }

    public void setMoniker(String moniker) {
        this.moniker = moniker;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
}
