spring: 
  application:  
    name: zipkin-server 
    
server: 
  port: 8020 #默认9411
  
zipkin:
   storage:
      type: mysql
      mysql: 
        host: 10.16.8.140
        port: 3306
        username: root
        password: mysql
        db: zipkin
