package cn.com.zsyk.crm.query.mapper;

import cn.com.zsyk.crm.query.entity.GUPolicymain;

import java.util.List;
import java.util.Map;

public interface GuPolicyMainMapper {

    /**
     * 根据权限统计保单数量
     * @param map
     * @return
     */
    int selectPolicyCountByRole(Map map);

    /**
     * 根据权限统计保费
     * @param map
     * @return
     */
    double selectPremiumCountByRole(Map map);
    /**
     * 根据客户代码查询客户的各个险类的总保额
     * @param map
     * @return
     */
    List<Map<String, Double>> selectInsuranceAmountByCustNo(List<String>  custNo);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUPOLICYMAIN
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String policyno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUPOLICYMAIN
     *
     * @mbggenerated
     */
    int insert(GUPolicymain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUPOLICYMAIN
     *
     * @mbggenerated
     */
    GUPolicymain selectByPrimaryKey(String policyno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUPOLICYMAIN
     *
     * @mbggenerated
     */
    List<GUPolicymain> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUPOLICYMAIN
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GUPolicymain record);
    List<GUPolicymain> selectByList(String stampTime);
    long selectAllCustCount(String stampTime);


}