package cn.com.zsyk.crm.query.mapper;

import java.util.List;
import java.util.Map;

import cn.com.zsyk.crm.query.bo.CustEventBaseInfo;
import cn.com.zsyk.crm.query.bo.RenwalEventBaseInfo;
import cn.com.zsyk.crm.query.entity.SysAutoRemind;

public interface SysAutoRemindMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table SYS_AUTO_REMIND
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String msgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table SYS_AUTO_REMIND
	 *
	 * @mbggenerated
	 */
	int insert(SysAutoRemind record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table SYS_AUTO_REMIND
	 *
	 * @mbggenerated
	 */
	SysAutoRemind selectByPrimaryKey(String msgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table SYS_AUTO_REMIND
	 *
	 * @mbggenerated
	 */
	List<SysAutoRemind> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table SYS_AUTO_REMIND
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysAutoRemind record);

	/**
	 * 按条件查询所有的事件列表客户列表
	 */
	@SuppressWarnings("rawtypes")
	List<CustEventBaseInfo> selectAllEventByUser(Map map);

	/**
	 * 按条件查询所有的续保列表客户列表
	 */
	@SuppressWarnings("rawtypes")
	List<RenwalEventBaseInfo> selectAllRenwalByUser(Map map);

}