package cn.com.zsyk.crm.common.mapper;

import cn.com.zsyk.crm.common.entity.SysOperLog;
import java.util.List;
import java.util.Map;

public interface SysOperLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sys_oper_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sys_oper_log
     *
     * @mbggenerated
     */
    int insert(SysOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sys_oper_log
     *
     * @mbggenerated
     */
    SysOperLog selectByPrimaryKey(Long seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sys_oper_log
     *
     * @mbggenerated
     */
    List<SysOperLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sys_oper_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysOperLog record);
    
    
    List<SysOperLog> selectByEntity(Map param);
}