###################  开发环境配置     ###################
info:
  log-switch: 
    service: true
  
server:
  port: 8082
  context-path: / #设定应用的context-path
    
spring:
  profiles: dev  
  application: 
    name: ${appName:crm-manage}
mybatis:
  mapper-packages:  cn.com.zsyk.crm.manage.mapper        #Mapper接口扫描目录
  mapper-locations: classpath:mapper/manage/*.xml       #xml文件扫描目录
  type-aliases-package: cn.com.zsyk.crm.manage.entity    #别名扫描目录  

logging:
  level:
     cn.com.zsyk.crm.manage.mapper : debug